(function(g){var window=this;'use strict';var Wl=function(e){e.publish("cardstatechange",e.BI()&&e.DI()?1:0)},lU=function(e,a){var r=g.BB(a),P=r?a:arguments;
for(r=r?0:1;r<P.length;r++){if(e==null)return;e=e[P[r]]}return e},EjB=function(e){var a=g.KO(e);
e=g.rF(e);return new g.I8(a.x,a.y,e.width,e.height)},bUa=function(e,a,r){var P=P===void 0?{}:P;
var B;return B=g.Eu(e,a,function(){g.bQ(B);r.apply(e,arguments)},P)},wg=function(e){e=g.oZ(e);
delete Lx[e];g.Ak(Lx)&&Yt&&Yt.stop()},gjB=function(){Yt||(Yt=new g.vP(function(){ty9()},20));
var e=Yt;e.isActive()||e.start()},ty9=function(){var e=g.f5();
g.K5(Lx,function(a){ZUb(a,e)});
g.Ak(Lx)||gjB()},px=function(e,a,r,P){g.oc.call(this);
if(!Array.isArray(e)||!Array.isArray(a))throw Error("Start and end parameters must be arrays");if(e.length!=a.length)throw Error("Start and end points must be the same length");this.T=e;this.D=a;this.duration=r;this.C=P;this.coords=[];this.progress=this.Z=0;this.L=null},ZUb=function(e,a){a<e.startTime&&(e.endTime=a+e.endTime-e.startTime,e.startTime=a);
e.progress=(a-e.startTime)/(e.endTime-e.startTime);e.progress>1&&(e.progress=1);e.Z=1E3/(a-e.L);e.L=a;OUN(e,e.progress);e.progress==1?(e.S=0,wg(e),e.onFinish(),e.kX()):e.isPlaying()&&e.Nt()},OUN=function(e,a){typeof e.C==="function"&&(a=e.C(a));
e.coords=Array(e.T.length);for(var r=0;r<e.T.length;r++)e.coords[r]=(e.D[r]-e.T[r])*a+e.T[r]},kPb=function(e,a){g.se.call(this,e);
this.coords=a.coords;this.x=a.coords[0];this.y=a.coords[1];this.z=a.coords[2];this.duration=a.duration;this.progress=a.progress;this.fps=a.Z;this.state=a.S},iU=function(e,a,r,P,B){px.call(this,a,r,P,B);
this.element=e},duN=function(e,a,r,P,B){if(a.length!=2||r.length!=2)throw Error("Start and end points must be 2D");
iU.call(this,e,a,r,P,B)},JCN=function(e){return Math.pow(e,3)},DuN=function(e){return 3*e*e-2*e*e*e},Vya=function(e){g.N.call(this);
this.T=e||window;this.S=[]},zl=function(e){return e.baseUrl||null},NL=function(e,a){return g.QX(g.ba(e,a),function(r){return!!r})},$uN=function(e,a,r){function P(CL){var nL=CL.hovercardButton;
if(!nL)return null;nL=nL.subscribeButtonRenderer;if(!nL)return null;var y3=h(nL.unsubscribedButtonText),aT=h(nL.subscribedButtonText);if(nL.subscribed){var $N=h(nL.subscriberCountWithUnsubscribeText);var F4=h(nL.subscriberCountText)}else $N=h(nL.subscriberCountText),F4=h(nL.subscriberCountWithSubscribeText);var ea=null;if(CL.signinEndpoint){ea=lU(CL,"signinEndpoint","webNavigationEndpointData","url");if(!ea){var EG,n5;ea=(n5=g.H((EG=nL.signInEndpoint)==null?void 0:EG.commandMetadata,g.d0))==null?
void 0:n5.url}if(!ea)return null}return y3&&(aT||ea)?{subscribed:nL.subscribed,subscribeText:y3,subscribeCount:$N,unsubscribeText:aT,unsubscribeCount:F4,enabled:nL.enabled,signinUrl:ea,classic:CL.useClassicSubscribeButton}:null}
function B(CL){if(CL){var nL=[],y3=CL.videoId;y3&&nL.push("v="+y3);(y3=CL.playlistId)&&nL.push("list="+y3);(CL=CL.startTimeSeconds)&&nL.push("t="+CL);return"/watch?"+nL.join("&")}}
function h(CL){if(!CL)return null;var nL=CL.simpleText;return nL?nL:CL.runs?g.ba(CL.runs,function(y3){return y3.text}).join(""):null}
a=a.endscreenElementRenderer;if(!a)return null;var c=a.style,y=a.endpoint||{},T=null,X=null,f=!1,A=null,U=null,C=null,G=null,O=!1,d=null,W=null,V=null,L=null,z=null,q=null;if(c==="VIDEO")g.H(y,g.lv)?T=g.H(y,g.lv).url:(q=g.H(y,g.g3),T=B(q)),X=!1,A=e,a.thumbnailOverlays?(f=a.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,U=h(f.text),f=f.style==="LIVE"):U=h(a.videoDuration);else if(c==="PLAYLIST")g.H(y,g.lv)?T=g.H(y,g.lv).url:(q=g.H(y,g.g3),T=B(q)),X=!1,A=e,C=h(a.playlistLength);else if(c===
"CHANNEL"){if(O=lU(y,"browseEndpoint","browseId"))G=O,T="/channel/"+G;X=!1;A="new";(O=!!a.isSubscribe)?d=P(a):W=h(a.subscribersText)}else c==="WEBSITE"?((V=lU(y,"urlEndpoint","url"))&&(T=V),X=!0,A="new",V=a.icon.thumbnails[0].url):c==="CREATOR_MERCHANDISE"&&(a.productPrice&&(L=h(a.productPrice)),a.additionalFeesText&&(z=h(a.additionalFeesText)),(X=lU(y,"urlEndpoint","url"))&&(T=X),X=!0,A="new");e=lU(a,"title","accessibility","accessibilityData","label");var M=a.endpoint?a.endpoint.clickTrackingParams:
null,m="";if(a.metadata){var cI=h(a.metadata);cI&&(m=cI)}return{id:"element-"+r,type:c,title:h(a.title),metadata:m,callToAction:h(a.callToAction),dY:a.image,iconUrl:V,left:Number(a.left),width:Number(a.width),top:Number(a.top),aspectRatio:Number(a.aspectRatio),startMs:Math.floor(Number(a.startMs)),endMs:Math.floor(Number(a.endMs)),videoDuration:U,vM:f,playlistLength:C,channelId:G,subscribeButton:d,subscribersText:W,isSubscribe:O,targetUrl:T||null,wQ:X,sessionData:M?{itct:M}:null,CcM:A,LC:e?e:null,
isPlaceholder:a.isPlaceholder,impressionUrls:NL(a.impressionUrls||[],zl),bY:NL(a.hovercardShowUrls||[],zl),clickUrls:NL(y.loggingUrls||[],zl),visualElement:g.C4(a.trackingParams),productPrice:L,additionalFeesText:z,watchEndpoint:q||null}},QUB=function(e,a){var r={startMs:Math.floor(Number(e.startMs)),
impressionUrls:NL(e.impressionUrls||[],zl),elements:NL(e.elements||[],function(P,B){return $uN(a,P,B)})};
e.trackingParams&&(r.visualElement=g.C4(e.trackingParams));return r},WTN=function(e){g.Vn.call(this,e);
this.L=this.endscreen=null;this.T={};this.Z={};this.C=this.B=null;this.Y=[];this.S=null;this.HW=!0;this.D=0;e=e.G();this.N=g.Bb(e)||g.cb(e);this.events=new g.Zc(this);g.x(this,this.events);this.events.j(this.player,g.SS("creatorendscreen"),this.onCueRangeEnter);this.events.j(this.player,g.sh("creatorendscreen"),this.onCueRangeExit);this.events.j(this.player,"resize",this.VX);this.events.j(window,"focus",this.wZH);this.load();var a=g.U9("STYLE");(g.h5("HEAD")[0]||document.body).appendChild(a);this.addOnDisposeCallback(function(){g.t5(a)});
a.sheet&&(a.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),a.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},lQN=function(e){return e.player.getVideoData().nB?"current":e.N?"new":"current"},xt=function(e){return e.player.G().playerStyle==="creator-endscreen-editor"},LTV=function(e){var a=e.player.getVideoData(),r=a.videoId;
e.L&&e.L.abort();r={method:"POST",onFinish:function(B){var h=e.L=null;B.status===200&&(B=B.responseText,B.substring(0,3)===")]}"&&(B=B.substring(3),h=JSON.parse(B),h=QUB(h,lQN(e))));IL(e,h)},
urlParams:{v:r},withCredentials:!0};e.N&&(r.urlParams.ptype="embedded");var P=a.ZK;P&&(r.postParams={ad_tracking:P});if(a=g.RQL(a))if(a=g.oD(a),a=g.BR(a))e.L=g.ge(a,r)},IL=function(e,a,r){r=r===void 0?!0:r;
e.player.Ai("creatorendscreen");e.B&&(e.B.dispose(),e.B=null,e.C.dispose(),e.C=null);for(var P=g.Z(Object.values(e.T)),B=P.next();!B.done;B=P.next())B.value.dispose();e.T={};e.Z={};e.Y.length>0&&(e.Y.forEach(function(y){y.dispose()}),e.Y.length=0);
e.S&&(g.BD(e.S,"ytp-ce-element-show"),e.S.setAttribute("aria-hidden","true"));e.D=0;if((e.endscreen=a)&&a.elements){r&&Yb9(e);r=[];P=new g.v_(a.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});r.push(P);e.player.G().T||(e.B=new g.v({K:"div",U:"ytp-ce-shadow"}),g.MY(e.player,e.B.element,4),e.C=new g.jq(e.B,200));for(P=0;P<a.elements.length;++P){B=a.elements[P];var h=wSa(e,B);if(h){e.T[B.id]=h;e.Z[B.id]=B;g.MY(e.player,h.element,4);var c=new g.v_(B.startMs,B.endMs,{id:"ytp-ce-element-"+
B.id,namespace:"creatorendscreen"});r.push(c);pSl(e,h,B)}else g.VJ(new g.I6("buildEndscreenElement null",B))}e.player.Ji(r);e.VX()}},Yb9=function(e){var a=g.Er(),r=g.bs();
r&&a&&e.endscreen.visualElement&&g.s7(g.xZ)(void 0,r,a,e.endscreen.visualElement)},wSa=function(e,a){var r=null;
switch(a.type){case "VIDEO":e={K:"div",WW:["ytp-ce-element","ytp-ce-video"],J:{tabindex:"0","aria-label":a.LC||"","aria-hidden":"true"},V:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-covering-image",J:Hl(a)},{K:"div",U:"ytp-ce-covering-shadow-top"},{K:"a",U:"ytp-ce-covering-overlay",J:{href:qL(e,a.targetUrl),tabindex:"-1"},V:[{K:"div",WW:["ytp-ce-video-title","ytp-webkit-ellipsis"],J:{dir:g.fT(a.title||"")},S1:a.title},{K:"div",U:a.vM?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
S1:a.videoDuration||void 0}]}]};r=new g.v(e);break;case "PLAYLIST":e={K:"div",WW:["ytp-ce-element","ytp-ce-playlist"],J:{tabindex:"0","aria-label":a.LC||"","aria-hidden":"true"},V:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-covering-image",J:Hl(a)},{K:"div",U:"ytp-ce-covering-shadow-top"},{K:"a",U:"ytp-ce-covering-overlay",J:{href:qL(e,a.targetUrl),tabindex:"-1"},V:[{K:"div",WW:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],J:{dir:g.fT(a.title||"")},S1:a.title},{K:"div",U:"ytp-ce-playlist-count",
V:[{K:"div",U:"ytp-ce-playlist-icon"},{K:"div",U:"ytp-ce-playlist-count-text",S1:a.playlistLength||void 0}]}]}]};r=new g.v(e);break;case "CHANNEL":r={K:"div",WW:["ytp-ce-element","ytp-ce-channel",a.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],J:{tabindex:"0","aria-label":a.LC||"","aria-hidden":"true"},V:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",V:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",
V:[{K:"div",U:"ytp-ce-expanding-overlay-body",V:[{K:"div",U:"ytp-ce-expanding-overlay-body-padding",V:[{K:"a",WW:["ytp-ce-channel-title","ytp-ce-link"],J:{href:qL(e,a.targetUrl),target:"_blank",tabindex:"-1",dir:g.fT(a.title||"")},S1:a.title},a.subscribeButton?{K:"div",U:"ytp-ce-subscribe-container",V:[{K:"div",U:"ytp-ce-channel-subscribe"}]}:"",a.subscribersText?{K:"div",U:"ytp-ce-channel-subscribers-text",S1:a.subscribersText}:"",a.metadata?{K:"div",WW:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],S1:a.metadata}:""]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",J:Hl(a)}]};r=new g.v(r);var P=g.o8(document,"div","ytp-ce-channel-subscribe",r.element)[0];if(a.subscribeButton&&a.channelId){g.rr(P,"ytp-ce-subscribe-button");if(e.player.G().T){var B=null;var h=a.sessionData.itct}else B="endscreen",h=null;B=new g.c6(a.subscribeButton.subscribeText,a.subscribeButton.subscribeCount,a.subscribeButton.unsubscribeText,a.subscribeButton.unsubscribeCount,!!a.subscribeButton.enabled,!!a.subscribeButton.classic,
a.channelId,!!a.subscribeButton.subscribed,B,h,e.player,!1);P.appendChild(B.element);e.Y.push(B)}break;case "WEBSITE":e={K:"div",WW:["ytp-ce-element","ytp-ce-website"],J:{tabindex:"0","aria-label":a.LC||"","aria-hidden":"true"},V:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",V:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",V:[{K:"div",U:"ytp-ce-expanding-overlay-body",V:[{K:"div",
U:"ytp-ce-expanding-overlay-body-padding",V:[{K:"div",U:"ytp-ce-website-title",J:{dir:g.fT(a.title||"")},S1:a.title},{K:"div",U:"ytp-ce-website-metadata",S1:a.metadata},{K:"a",WW:["ytp-ce-website-goto","ytp-ce-link"],J:{href:qL(e,a.targetUrl),target:"_blank",tabindex:"-1"},S1:a.callToAction}]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",J:Hl(a)},{K:"div",U:"ytp-ce-expanding-icon",J:iU5(a.iconUrl)}]};r=new g.v(e);break;case "CREATOR_MERCHANDISE":r="",a.productPrice&&(r={K:"div",U:"ytp-ce-merchandise-price-container",
V:[{K:"div",U:"ytp-ce-merchandise-price",S1:a.productPrice}]},a.additionalFeesText&&r.V.push({K:"div",U:"ytp-ce-merchandise-additional-fees",S1:a.additionalFeesText})),e={K:"div",WW:["ytp-ce-element","ytp-ce-merchandise"],J:{tabindex:"0","aria-label":a.LC||"","aria-hidden":"true"},V:[{K:"div",U:"ytp-ce-element-shadow"},{K:"div",U:"ytp-ce-expanding-overlay",V:[{K:"div",U:"ytp-ce-expanding-overlay-hider"},{K:"div",U:"ytp-ce-expanding-overlay-background"},{K:"div",U:"ytp-ce-expanding-overlay-content",
V:[{K:"div",U:"ytp-ce-expanding-overlay-body",V:[{K:"div",U:"ytp-ce-expanding-overlay-body-padding",V:[{K:"div",U:"ytp-ce-merchandise-title",J:{dir:g.fT(a.title||"")},S1:a.title},r,{K:"div",U:"ytp-ce-merchandise-metadata",S1:a.metadata},{K:"a",WW:["ytp-ce-merchandise-goto","ytp-ce-link"],J:{href:qL(e,a.targetUrl),target:"_blank",tabindex:"-1"},S1:a.callToAction}]}]}]}]},{K:"div",U:"ytp-ce-expanding-image",J:Hl(a)},{K:"div",U:"ytp-ce-merchandise-invideo-cta-container",V:[{K:"div",U:"ytp-ce-merchandise-invideo-cta",
S1:a.callToAction||void 0}]}]},r=new g.v(e)}a.isPlaceholder&&g.rr(r.element,"ytp-ce-placeholder");return r},Hl=function(e){if(e.dY)var a=e.dY.thumbnails;
return iU5(a?a[a.length-1].url:null)},iU5=function(e){return e?{style:"background-image: url("+e+")"}:{}},pSl=function(e,a,r){function P(T){T&&(a.listen("blur",function(){T.style.display!="none"&&e.HW&&T.focus()}),a.j(T,"focus",h),a.j(T,"blur",c))}
function B(T){e.D+=T;e.D>0?(g.rr(a.element,"ytp-ce-force-expand"),vl(e,r.id,!0)):(g.BD(a.element,"ytp-ce-force-expand"),g.BD(a.element,"ytp-ce-element-hover"),vl(e,r.id,!1))}
function h(){B(1)}
function c(){B(-1)}
a.listen("mouseenter",function(){zA9(e,a,r)});
a.listen("mouseleave",function(){NO9(e,a,r)});
e.player.G().T||a.listen("click",function(){g.rr(a.element,"ytp-ce-element-hover")});
a.listen("click",function(T){xuM(e,r,T)});
a.listen("keypress",function(T){xuM(e,r,T)});
a.listen("focus",function(){zA9(e,a,r)});
a.listen("blur",function(){NO9(e,a,r)});
a.listen("touchstart",function(){zA9(e,a,r)});
var y=g.nO("ytp-ce-expanding-overlay-hider",a.element);y&&a.j(y,"touchstart",function(T){T.stopPropagation();g.BD(a.element,"ytp-ce-element-hover");g.BD(a.element,"ytp-ce-force-expand")});
a.listen("keydown",function(T){e.HW=T.keyCode===9&&!T.shiftKey});
P(g.nO("ytp-sb-subscribe",a.element));P(g.nO("ytp-sb-unsubscribe",a.element));a.listen("focus",h);a.listen("blur",c)},xuM=function(e,a,r){if(a.targetUrl&&(!r||r.type!=="keypress"||r.keyCode===13)){for(var P=r.target;P&&!g.ac(P,"ytp-ce-element");){g.ac(P,"subscribe-label")&&IQB(e,a);
if(g.ac(P,"ytp-ce-channel-subscribe"))return;P=P.parentElement||null}if(!P||g.ac(P,"ytp-ce-element-hover")){r.preventDefault();r.stopPropagation();if(P=e.T[a.id])NO9(e,P,a),P.element.blur();if(r.ctrlKey||r.metaKey||a.CcM==="new")IQB(e,a),e.player.sendVideoStatsEngageEvent(17,void 0),e.player.pauseVideo(),r=g.oD(qL(e,a.targetUrl)),r=g.BR(r),g.xg(r,void 0,a.sessionData);else{var B=g.tZ(e.player.G())||e.player.getVideoData().nB,h=function(){var c=qL(e,a.targetUrl),y=a.sessionData,T=a.watchEndpoint,X=
g.KG(c);B&&X&&(X.v||X.list)?e.player.nY(X.v,y,X.list,!1,void 0,T||void 0):g.Nd(c,y)};
IQB(e,a,function(){e.player.sendVideoStatsEngageEvent(17,h)})}}}},qL=function(e,a){e=e.player.G();
if(a){if(a.startsWith("//"))return e.protocol+":"+a;if(a.startsWith("/"))return g.Vg(e)+a}else return"";return a},zA9=function(e,a,r){g.ac(a.element,"ytp-ce-element-hover")||(r.type==="VIDEO"||r.type==="PLAYLIST"?g.rr(a.element,"ytp-ce-element-hover"):e.player.G().T?(new g.vP(function(){g.rr(a.element,"ytp-ce-element-hover")},200)).start():g.rr(a.element,"ytp-ce-element-hover"),RL(e,r.bY),vl(e,r.id,!0))},NO9=function(e,a,r){g.BD(a.element,"ytp-ce-element-hover");
g.BD(a.element,"ytp-ce-force-expand");vl(e,r.id,!1)},vl=function(e,a,r){e.B&&(r?e.C.show():e.C.hide());
for(var P=g.Z(Object.keys(e.T)),B=P.next();!B.done;B=P.next())B=B.value,B!==a&&g.cD(e.T[B].element,"ytp-ce-element-shadow-show",r)},RL=function(e,a,r){function P(){h||(B++,B===a.length&&(c.stop(),r&&r()))}
if(!a||a.length===0||xt(e))r&&r();else{a=HUw(e,a);var B=0,h=!1,c=new g.vP(function(){h=!0;r&&r()},1E3,e);
c.start();for(e=0;e<a.length;e++)g.Lu(a[e],P)}},IQB=function(e,a,r){RL(e,a.clickUrls,r);
(e=g.bs())&&a.wQ&&g.js(e,a.visualElement)},HUw=function(e,a){var r=e.player.getVideoData().clientPlaybackNonce;
e=e.player.getCurrentTime().toFixed(2);r={CPN:r,AD_CPN:r,MT:e};e=[];for(var P=0;P<a.length;P++)e.push(qbZ(a[P],r));return e},qbZ=function(e,a){return e.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(r){var P=unescape(r);
P=P.substring(1,P.length-1);return a[P]?escape(a[P]):r})},vjG=function(e){return typeof e==="string"?e:""},SJ=function(e,a,r){for(var P in a)if(a[P]===e)return e;
return r},RAl=function(e,a,r,P){this.value=e;
this.target=a;this.showLinkIcon=r;this.S=P},sz=function(e){return e.value?e.value:null},mC=function(e){if(!e)return null;
var a=g.oD(vjG(e.value));a=g.BR(a);if(!a)return null;var r=SJ(e.target,SbB,"current");if(r==null)e=null;else{var P=e.show_link_icon;e=new RAl(a,r,P==="true"||P==="false"?P==="true":!0,e.pause_on_navigation!=null?e.pause_on_navigation:!0)}return e},sUl=function(e,a,r){this.type=e;
this.trigger=a;this.url=r},MyN=function(e){if(!e)return null;
var a=SJ(e.type,muZ),r=SJ(e.trigger,FT5);e=e.url;e=Array.isArray(e)&&e.length?e[0]:e;e=mC(e?e:null);return a?new sUl(a,r,e):null},jUa=function(e,a,r,P,B){this.id=e;
this.type=a;this.style=r;this.data=B;this.action=P||[]},u6l=function(e,a){return g.tw(e.action,a)},KTM=function(e,a){this.context=e;
this.S=a},ek5=function(e){return e.customMessage?Fy("div","iv-card-message",e.customMessage):""},ML=function(e,a){e="background-image: url("+e+");";
var r=[];a&&r.push(a);return{K:"div",U:"iv-card-image",J:{style:e},V:r}},a$M=function(e){if(!e.metaInfo||e.metaInfo.length===0)return"";
var a=[];e=g.Z(e.metaInfo);for(var r=e.next();!r.done;r=e.next())a.push(Fy("li","",r.value));return{K:"ul",U:"iv-card-meta-info",V:a}},Fy=function(e,a,r){a?typeof a==="string"?a={"class":a}:Array.isArray(a)&&(a={"class":a.join(" ")}):a={};
a.dir=g.fT(r);return{K:e,J:a,S1:r}},rqB=function(e){if(!e.customMessage)return"";
var a=["iv-card-action","iv-card-primary-link"],r={};e.Q$&&(a.push("iv-card-action-icon"),r.style="background-image: url("+e.Q$+");");r.dir=g.fT(e.customMessage);var P=[{K:"span",S1:e.customMessage}];e.showLinkIcon&&(P.push("\u00a0"),P.push({K:"span",U:"iv-card-link-icon"}));return{K:"div",WW:a,J:r,V:P}},jJ=function(e,a,r,P){if(P){a=g.Z(a);
for(var B=a.next();!B.done;B=a.next())e.S(B.value,P,r.id,r.sessionData,r.Bo.click,5)}},P5N=function(e,a){this.merchant=e;
this.price=a},BNV=function(e){var a;
(a=e)&&!(a=e.length>1?e.charAt(0)==="/"&&e.charAt(1)!=="/":e==="/")&&(a=e.replace(/^(https?:)?\/\//,"").split("/",1),a=!a||a.length<1||!a[0]?[]:a[0].toLowerCase().split(".").reverse(),a=a[0]==="com"&&a[1]==="youtube"||a[0]==="be"&&a[1]==="youtu");return a?e.indexOf("/redirect?")===-1:!1},hk9=function(e,a){return a?a:BNV(e)?"current":"new"},uU=function(e,a){g.N.call(this);
var r=this;this.element=e;this.context=a;this.rP=!1;this.GQ=new Map;this.ym=new Map;this.context.W.addEventListener(g.SS("annotations_module"),function(P){(P=r.GQ.get(P))&&P.apply(r)});
this.context.W.addEventListener(g.sh("annotations_module"),function(P){(P=r.ym.get(P))&&P.apply(r)})},Kx=function(e,a,r,P,B,h,c){e.context.S.listen(a,"click",function(y){e.i8(r,P,B,h||[],c||0,y)});
e.context.S.listen(a,"touchstart",function(){e.rP=!1});
e.context.S.listen(a,"touchmove",function(){e.rP=!0})},cqN=function(e){var a;
return((a=g.H(e,g.lv))==null?0:a.url)?g.H(e,g.lv).url:(e=g.H(e,g.g3))&&e.videoId?(a="/watch?v="+e.videoId,e.playlistId&&(a+="&list="+e.playlistId),e.index&&(a+="&index="+e.index),e.startTimeSeconds&&(a+="&t="+e.startTimeSeconds),a):null},ed=function(e,a,r){return{Ia:(e.impressionLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
click:(r.loggingUrls||[]).map(function(P){return P.baseUrl||""}),
close:(a.dismissLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
aK:(a.impressionLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""}),
Zb:(a.clickLoggingUrlsV2s||[]).map(function(P){return P.baseUrl||""})}},oLZ=function(e,a,r){uU.call(this,a,r);
var P=this;this.W=e;this.eventId=null;this.T$=this.e1=this.ID=this.B=this.isInitialized=!1;this.cards=[];this.HA=this.C=this.Cf=this.Z=this.Uo=this.S=null;this.HW=[];this.oH=this.Y=this.uc=this.Lf=null;this.D=0;this.Eo=new g.vP(function(){},r.iW.oi?4E3:3E3);
g.x(this,this.Eo);this.k$=new g.vP(function(){});
g.x(this,this.k$);this.TQ=new KTM(r,function(B,h,c,y,T,X){Kx(P,B,h,c,y,T,X)});
this.N=new g.v({K:"div",U:"iv-drawer",J:{id:"iv-drawer"},V:[{K:"div",U:"iv-drawer-header",J:{"aria-role":"heading"},V:[{K:"span",U:"iv-drawer-header-text"},{K:"button",WW:["iv-drawer-close-button","ytp-button"],J:{"aria-label":"Hide cards",tabindex:"0"}}]},{K:"div",U:"iv-drawer-content"}]});g.x(this,this.N);this.L=this.N.element;this.PW=new g.jq(this.N,330);g.x(this,this.PW);this.bv=g.nO("iv-drawer-header-text",this.L);this.T=g.nO("iv-drawer-content",this.L);this.addCueRange(0,r.videoData.lengthSeconds*
1E3,"",function(){P.ID&&a3(P,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(P.ID=P.B)&&r$(P)});
this.XM=new g.Zc(this);g.x(this,this.XM);this.W.addEventListener("videodatachange",this.zm.bind(this))},nLw=function(e,a){a=a.data;
a.autoOpenMs&&e.addCueRange(a.autoOpenMs,0x8000000000000,"",function(){a3(e,"YOUTUBE_DRAWER_AUTO_OPEN")});
a.autoCloseMs&&e.addCueRange(a.autoCloseMs,0x8000000000000,"",function(){r$(e)});
var r=a.headerText;g.ZF(e.bv,r);e.C&&(e.W.X("player_tooltip_data_title_killswitch")?e.C.setAttribute("title",r):e.C.setAttribute("data-tooltip-title",r));a.eventId&&(e.eventId=a.eventId);e.Lf=g.C4(a.trackingParams);e.Y=g.C4(a.closeTrackingParams);e.uc=g.C4(a.iconTrackingParams)},yqB=function(e,a){var r=a.cardId?a.cardId:"cr:"+e.D,P=e.W.G().experiments.FM("enable_error_corrections_infocard_web_client");
if(!a.content&&a.teaser.simpleCardTeaserRenderer&&P){var B=a.teaser.simpleCardTeaserRenderer,h=a.icon?a.icon.infoCardIconRenderer:null;if(B.channelAvatar&&B.channelAvatar.thumbnails&&B.channelAvatar.thumbnails.length>0)var c=PY(B.channelAvatar.thumbnails,22,22).url;a={id:r,timestamp:e.D,type:"simple",teaserText:g.yd(B.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:{},sponsored:!1,Bo:{},jV:null,FJ:B.trackingParams?
g.C4(B.trackingParams):null,uc:h&&h.trackingParams?g.C4(h.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Q$:null,title:"",customMessage:"",url:null,onClickCommand:B.onTapCommand||null,E6:c};BY(e,a)}else{var y;if((y=a.content)==null?0:y.simpleCardContentRenderer){if(!a.cueRanges.length)return;c=(B=a.content)==null?void 0:B.simpleCardContentRenderer;B=a.teaser.simpleCardTeaserRenderer;h=a.icon?a.icon.infoCardIconRenderer:null;a={id:r,timestamp:e.D,type:"simple",teaserText:g.yd(B.message),
teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:hy(e,r,a,c),sponsored:!1,Bo:ed(c,B,c.command),jV:c.trackingParams?g.C4(c.trackingParams):null,FJ:B.trackingParams?g.C4(B.trackingParams):null,uc:h&&h.trackingParams?g.C4(h.trackingParams):null,imageUrl:PY(c.image.thumbnails,290,290).url,displayDomain:c.displayDomain?g.yd(c.displayDomain):null,showLinkIcon:!!c.showLinkIcon,Q$:null,title:c.title?g.yd(c.title):"",
customMessage:c.callToAction?g.yd(c.callToAction):"",url:g.H(c.command,g.lv).url?mC({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:g.H(c.command,g.lv).url}):null,onClickCommand:null};BY(e,a)}else{var T;if((T=a.content)==null?0:T.collaboratorInfoCardContentRenderer){if(!a.cueRanges.length)return;c=(h=a.content)==null?void 0:h.collaboratorInfoCardContentRenderer;B=a.teaser.simpleCardTeaserRenderer;h=a.icon?a.icon.infoCardIconRenderer:null;a={id:r,timestamp:e.D,type:"collaborator",
teaserText:g.yd(B.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:hy(e,r,a,c),sponsored:!1,Bo:ed(c,B,c.endpoint),jV:c.trackingParams?g.C4(c.trackingParams):null,FJ:B.trackingParams?g.C4(B.trackingParams):null,uc:h&&h.trackingParams?g.C4(h.trackingParams):null,channelId:g.H(c.endpoint,g.sT).browseId,customMessage:c.customText?g.yd(c.customText):null,profileImageUrl:PY(c.channelAvatar.thumbnails,290,
290).url,title:c.channelName?g.yd(c.channelName):"",metaInfo:[c.subscriberCountText?g.yd(c.subscriberCountText):""],url:mC({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:g.H(c.endpoint,g.sT).canonicalBaseUrl?g.H(c.endpoint,g.sT).canonicalBaseUrl:"/channel/"+g.H(c.endpoint,g.sT).browseId}),onClickCommand:null};BY(e,a)}else{var X;if((X=a.content)==null?0:X.playlistInfoCardContentRenderer){if(!a.cueRanges.length)return;var f;c=(f=a.content)==null?void 0:f.playlistInfoCardContentRenderer;
B=a.teaser.simpleCardTeaserRenderer;h=a.icon?a.icon.infoCardIconRenderer:null;a={id:r,timestamp:e.D,type:"playlist",teaserText:g.yd(B.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:hy(e,r,a,c),sponsored:!1,Bo:ed(c,B,c.action),jV:c.trackingParams?g.C4(c.trackingParams):null,FJ:B.trackingParams?g.C4(B.trackingParams):null,uc:h&&h.trackingParams?g.C4(h.trackingParams):null,aP:PY(c.playlistThumbnail.thumbnails,
258,290).url,customMessage:c.customMessage?g.yd(c.customMessage):null,playlistVideoCount:g.yd(c.playlistVideoCount),title:c.playlistTitle?g.yd(c.playlistTitle):"",metaInfo:[c.channelName?g.yd(c.channelName):"",c.videoCountText?g.yd(c.videoCountText):""],url:mC({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:cqN(c.action)}),onClickCommand:null};BY(e,a)}else{var A;if((A=a.content)==null?0:A.videoInfoCardContentRenderer){if(!a.cueRanges.length)return;var U;c=(U=a.content)==
null?void 0:U.videoInfoCardContentRenderer;B=a.teaser.simpleCardTeaserRenderer;h=a.icon?a.icon.infoCardIconRenderer:null;a={id:r,timestamp:e.D,type:"video",teaserText:g.yd(B.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:hy(e,r,a,c),sponsored:!1,Bo:ed(c,B,c.action),jV:c.trackingParams?g.C4(c.trackingParams):null,FJ:B.trackingParams?g.C4(B.trackingParams):null,uc:h&&h.trackingParams?g.C4(h.trackingParams):
null,aP:PY(c.videoThumbnail.thumbnails,258,290).url,videoDuration:c.lengthString?g.yd(c.lengthString):null,customMessage:c.customMessage?g.yd(c.customMessage):null,title:c.videoTitle?g.yd(c.videoTitle):"",metaInfo:[c.channelName?g.yd(c.channelName):"",c.viewCountText?g.yd(c.viewCountText):""],isLiveNow:!!c.badge,url:mC({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:cqN(c.action)}),onClickCommand:null};BY(e,a)}}}}}e.D++},PY=function(e,a,r){for(var P=-1,B=-1,h=0;h<e.length;h++){if(e[h].height===
a||e[h].width===r)return e[h];
((e[h].height||0)<a||(e[h].width||0)<r)&&(P<0||(e[P].height||0)<(e[h].height||0)||(e[P].width||0)<(e[h].width||0))?P=h:((e[h].height||0)>=a||(e[h].width||0)>=r)&&(B<0||(e[B].height||0)>(e[h].height||0)||(e[B].width||0)>(e[h].width||0))&&(B=h)}return e[B>=0?B:P]},hy=function(e,a,r,P){return{feature:r.feature?r.feature:"cards",
src_vid:e.context.videoData.videoId,annotation_id:a,ei:e.context.videoData.eventId||"",itct:P.trackingParams||""}},XJw=function(e,a){if(a=TNZ(e,a))a===e.S&&(e.S=null),e.W.removeCueRange(a.PG.id),g.t5(a.KJ),g.k9(e.cards,a),e.JY(),cY(e)},a3=function(e,a,r){if(!e.B){e.PW.show();
e.Uo=new g.vP(function(){g.rr(e.context.W.getRootNode(),g.to.IV_DRAWER_OPEN)},0);
e.Uo.start();e.XM.j(e.T,"mousewheel",function(c){e.Eo.start();c.preventDefault();c=c||window.event;var y=0;c.type=="MozMousePixelScroll"?y=0==(c.axis==c.HORIZONTAL_AXIS)?c.detail:0:window.opera?y=c.detail:y=c.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?c.wheelDeltaY/-30:c.wheelDeltaY/-1.2:c.wheelDelta/-1.6:c.wheelDeltaY/-3;if(c=y)e.T.scrollTop+=c});
e.B=!0;var P=g.bs();P&&e.Lf&&e.Y&&g.F_(P,[e.Lf,e.Y]);a={TRIGGER_TYPE:a};for(var B=g.Z(e.cards),h=B.next();!h.done;h=B.next())h=h.value,h.g7||(h.g7=!0,f$b(e.context.logger,h.PG.Bo.Ia,a)),P&&g.F_(P,[h.PG.jV]);Wl(e.W);r&&(e.Z=new g.vP(function(){e.Cf=e.C;e.HA.focus()},330),e.Z.start())}},r$=function(e){e.B&&(e.PW.hide(),g.du(e.XM),g.BD(e.context.W.getRootNode(),g.to.IV_DRAWER_OPEN),e.B=!1,Wl(e.W),e.Z&&e.Z.stop(),e.Z=new g.vP(function(){e.Cf&&(e.Cf.focus(),e.Cf=null)},330),e.Z.start())},AqB=function(e){g.PD(e.EM(),
[g.to.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.MY(e.W,e.L,5);e.Qs();e.C=g.nO("ytp-cards-button",e.W.getRootNode());e.HA=g.nO("iv-drawer-close-button",e.L);e.isInitialized=!0},UXB=function(e){e.HW.push(g.jA("iv-teaser-shown",e.R0,e));
e.HW.push(g.jA("iv-teaser-hidden",e.MR,e));e.HW.push(g.jA("iv-teaser-clicked",e.pw,e));e.T$=!0},C5b=function(e,a){var r;
return a.onClickCommand&&((r=g.H(a.onClickCommand,g.v8B))==null?void 0:r.targetId)==="engagement-panel-error-corrections"?(e.oH=a,!0):!1},G5N=function(e,a){e.oH=a;
var r=e.W.getVideoData();if(!r)return!1;r=g.jP(r);if(r==null?0:r.markersMap)for(var P,B=0;((P=r)==null?void 0:P.markersMap.length)>B;B++){var h=void 0,c=(h=r)==null?void 0:h.markersMap[B];if(c.key==="ERROR_CORRECTION_MARKERS"&&(h=void 0,(c=(h=c.value)==null?void 0:h.markers)&&c.length>0))return P=void 0,a.startMs=((P=g.H(c[0],g.f23))==null?void 0:P.timeRangeStartMillis)||0,e.oH=null,!0}return!1},BY=function(e,a){if(!C5b(e,a)||G5N(e,a)){var r=ELN(e,a);
if(r){var P={PG:a,KJ:r.element,g7:!1};if(a.onClickCommand)e.W.X("web_infocards_teaser_show_logging_fix")&&(e.T$||UXB(e),XJw(e,a.id),r=e.findLastIndex(P),g.NM(e.cards,r,0,P));else{e.isInitialized||AqB(e);XJw(e,a.id);var B=e.findLastIndex(P);g.NM(e.cards,B,0,P);r.Kf(e.T,B);e.JY()}a.autoOpen?e.addCueRange(a.startMs,0x8000000000000,a.id,function(){e.B||(e.S=P,cY(e),b0N(e,P),a3(e,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(r=e.context.W.getCurrentTime()*1E3,r<5E3&&r>a.startMs&&t5M(e,P),e.addCueRange(a.startMs,
a.startMs+1,a.id,function(){t5M(e,P)}),cY(e))}}},ELN=function(e,a){switch(a.type){case "simple":e=e.TQ;
var r=a.displayDomain?{K:"div",U:"iv-card-image-text",S1:a.displayDomain}:void 0;var P=rqB(a);r={K:"div",WW:["iv-card"],V:[{K:"a",U:"iv-click-target",J:{href:a.url?sz(a.url)||"":""},V:[ML(a.imageUrl,r),{K:"div",U:"iv-card-content",V:[Fy("h2",void 0,a.title),P]}]}]};r=new g.v(r);jJ(e,g.co("iv-click-target",r.element),a,a.url);a=r;break;case "collaborator":e=e.TQ;r={K:"div",WW:["iv-card","iv-card-channel"],V:[{K:"a",WW:["iv-click-target"],J:{href:sz(a.url)||"","data-ytid":a.channelId},V:[ML(a.profileImageUrl),
{K:"div",U:"iv-card-content",V:[ek5(a),{K:"h2",U:"iv-card-primary-link",S1:a.title},a$M(a)]}]}]};r=new g.v(r);jJ(e,g.co("iv-click-target",r.element),a,a.url);a=r;break;case "playlist":e=e.TQ;r={K:"div",WW:["iv-card","iv-card-playlist"],V:[{K:"a",U:"iv-click-target",J:{href:sz(a.url)||""},V:[ML(a.aP,{K:"div",U:"iv-card-image-overlay",V:[{K:"span",U:"iv-card-playlist-video-count",S1:a.playlistVideoCount}]}),{K:"div",U:"iv-card-content",V:[ek5(a),Fy("h2","iv-card-primary-link",a.title),a$M(a)]}]}]};
r=new g.v(r);jJ(e,g.co("iv-click-target",r.element),a,a.url);a=r;break;case "productListing":e=e.TQ;var B=a.offers.length!=0;r=["iv-card"];P="";var h=rqB(a);B&&(r.push("iv-card-product-listing"),P="iv-card-primary-link",h=a.offers[0],B=[],h.price&&B.push({K:"div",U:"iv-card-offer-price",S1:h.price}),h.merchant&&B.push({K:"div",U:"iv-card-offer-merchant",S1:h.merchant}),h={K:"div",V:B});B=a.url?sz(a.url)||"":"";r={K:"div",WW:r,J:{tabindex:"0"},V:[{K:"a",WW:["iv-card-image","iv-click-target"],J:{style:"background-image: url("+
a.imageUrl+");",href:B,"aria-hidden":"true",tabindex:"-1"}},{K:"div",U:"iv-card-content",V:[a.sponsored?{K:"div",U:"iv-card-sponsored",V:["Sponsored",{K:"div",U:"iv-ad-info-container",V:[{K:"div",U:"iv-ad-info",S1:"{{adInfo}}"},{K:"div",U:"iv-ad-info-icon-container",V:[{K:"div",U:"iv-ad-info-icon"},{K:"div",U:"iv-ad-info-callout"}]}]}]}:"",{K:"a",U:"iv-click-target",J:{href:B},V:[Fy("h2",P,a.title),h]}]}]};r=new g.v(r);P=g.U9("span");g.ZF(P,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
r.vO(P,"adInfo");jJ(e,g.co("iv-click-target",r.element),a,a.url);a=r;break;case "video":e=e.TQ;P=a.videoDuration?{K:"span",U:"iv-card-video-duration",S1:a.videoDuration}:void 0;h=a.isLiveNow?{K:"span",WW:["yt-badge","yt-badge-live"],S1:"LIVE NOW"}:null;B={K:"div",WW:["iv-card","iv-card-video"],V:[{K:"a",U:"iv-click-target",J:{href:((r=a.url)==null?void 0:sz(r))||""},V:[ML(a.aP,P),{K:"div",U:"iv-card-content",V:[ek5(a),Fy("h2","iv-card-primary-link",a.title),a$M(a),h]}]}]};r=new g.v(B);jJ(e,g.co("iv-click-target",
r.element),a,a.url);a=r;break;default:return null}return a},gLB=function(e){if(e.S)return e.S.PG.type==="productListing";
if(e.W.X("enable_wn_infocards")){var a;return!((a=e.cards)==null||!a.length)&&g.tK(e.cards,function(r){return r.PG.type==="productListing"})}return g.tK(e.cards,function(r){return r.PG.type==="productListing"})},cY=function(e){g.cD(e.W.getRootNode(),"ytp-cards-shopping-active",gLB(e))},t5M=function(e,a){if(!g.ac(e.W.getRootNode(),"ytp-cards-teaser-shown")){if(e.S!==a){var r=g.bs(),P=e.S?e.S.PG.uc:e.uc;
r&&P&&g.M9(r,[P]);e.S=a;cY(e)}(r=e.isInitialized&&e.EM().style.display=="none")||(r=e.context.W.getPlayerState(),P=r===0&&e.context.W.getCurrentTime()===0,r=!(r===1||r===3||P));if(!r&&a.PG.teaserDurationMs){var B;r={teaserText:a.PG.teaserText,durationMs:a.PG.teaserDurationMs,onClickCommand:a.PG.onClickCommand,E6:(B=a.PG.E6)!=null?B:null};e.W.Qd(!0,r)}e.k$.isActive()||((!e.B||!e.Eo.isActive()&&e.e1)&&b0N(e,a),e.k$.start(910+a.PG.teaserDurationMs))}},b0N=function(e,a){e.N.oD?(a=new px([0,
e.T.scrollTop],[0,a.KJ.offsetTop],600,DuN),e.context.B.listen(a,"animate",function(r){e.T.scrollTop=r.y}),e.context.B.listen(a,"finish",function(r){e.T.scrollTop=r.y}),a.play()):(e.N.Nr(!0),e.T.scrollTop=a.KJ.offsetTop,e.N.Nr(!1))},o3=function(e){return e.S&&e.S.PG?e.S.PG:e.cards[0]&&e.cards[0].PG?e.cards[0].PG:null},TNZ=function(e,a){return g.tw(e.cards,function(r){return r.PG.id===a})},nq=function(e,a,r){uU.call(this,e,a);
this.annotation=r;this.isActive=!1},Z0G=function(e){var a=e.annotation.data;
"start_ms"in a&&"end_ms"in a&&e.addCueRange(Number(a.start_ms),Number(a.end_ms),e.annotation.id,function(){e.show()},function(){e.hide()})},yo=function(e,a,r){nq.call(this,e,a,r);
this.T=null;this.D=!1;this.B=null;this.L=!1;this.S=this.Z=this.C=null},O0w=function(e,a){var r=r===void 0?0:r;
var P=EjB(a).width;g.j2(a,P);r=new duN(a,[P,a.offsetTop],[P-P-r,a.offsetTop],200,JCN);g.x(e,r);e.context.B.listen(r,"begin",function(){g.PQ(a,!0)});
r.play()},JqB=function(e,a){if(a.channel_name){var r=e.createElement({K:"div",
WW:["iv-branding-context-name"],S1:a.channel_name}),P=e.createElement({K:"div",WW:["iv-branding-context-subscribe"]}),B=a.standalone_subscribe_button_data;B&&(e.S=new g.c6(B.subscribeText,B.subscribeCount,B.unsubscribeText,B.unsubscribeCount,!!B.enabled,!!B.classic,a.channel_id,!!B.subscribed,B.feature,a.session_data.itct,e.context.W,!1),e.S.Kf(P));var h=e.createElement({K:"div",WW:["iv-branding-context-subscribe-caret"]}),c=e.createElement({K:"div",WW:["branding-context-container-inner"]});c.appendChild(h);
c.appendChild(r);c.appendChild(P);g.PQ(c,!1);var y=e.createElement({K:"div",WW:["branding-context-container-outer"]});y.appendChild(c);g.vo(y,"right",a.image_width+"px");g.G7(e.EM(),y);e.B=new g.vP(function(){k5B(e,c,y)},500);
g.x(e,e.B);e.context.S.listen(e.EM(),"mouseover",function(){dX8(e,c,y,h,a.image_height)});
e.context.S.listen(e.EM(),"mouseout",function(){e.B.start()})}},dX8=function(e,a,r,P,B){e.B.stop();
if(!e.L){var h=g.rF(a);e.S||(a.style.width=g.Mh(h.width,!0),r.style.width=g.Mh(h.width,!0));g.vo(P,"top",h.height-Math.max(Math.min(h.height,B)/2+10,20)+"px");g.vo(P,"right","1px");e.L=!0;g.PQ(a,!0);e.C=new g.vP(function(){g.rr(this.EM(),"iv-branding-active")},0,e);
e.C.start()}},k5B=function(e,a,r){g.BD(e.EM(),"iv-branding-active");
e.Z=new g.vP(function(){g.PQ(a,!1);e.S||(r.style.width=g.Mh(0,!0))},250);
e.Z.start();e.L=!1},DX9=function(e,a,r,P,B,h,c){this.S=e;
this.B=a;this.iW=r;this.videoData=P;this.logger=B;this.W=h;this.T=c},V5N=function(e,a,r){nq.call(this,e,a,r);
var P=this;this.Y=this.isCollapsed=this.N=!1;this.Z=5E3;this.T=this.B=this.S=this.L=null;this.D=this.createElement({K:"div",WW:["iv-promo-contents"]});this.C=new g.vP(function(){P.S.setAttribute("aria-hidden","true");g.PQ(P.B,!1);g.PQ(P.T,!0)},700,this);
g.x(this,this.C)},Q4b=function(e){var a=e.annotation.data;
if(e.annotation.style==="cta")var r=6;else if(e.annotation.style==="video"||e.annotation.style==="playlist")r=7;e.Z=a.collapsedelay_ms||e.Z;var P=["iv-promo","iv-promo-inactive"];e.EM().setAttribute("aria-hidden","true");e.EM().setAttribute("aria-label","Promotion");e.EM().tabIndex=0;var B=e.annotation.ju(),h=a.image_url;if(h){var c=e.createElement({K:"div",WW:["iv-promo-img","iv-click-target"]});h=e.createElement({K:"img",J:{src:h,"aria-hidden":"true"}});c.appendChild(h);a.video_duration&&!a.is_live?
(h=e.createElement({K:"span",U:"iv-promo-video-duration",S1:a.video_duration}),c.appendChild(h)):a.playlist_length&&(h=e.createElement({K:"span",U:"iv-promo-playlist-length",S1:a.playlist_length.toString()}),c.appendChild(h));B&&Kx(e,c,B,e.annotation.id,a.session_data,void 0,r)}B?(h=e.createElement({K:"a",U:"iv-promo-txt"}),g.T1(h,sz(B)),e.S=h):e.S=e.createElement({K:"div",U:"iv-promo-txt"});switch(e.annotation.style){case "cta":case "website":var y=e.createElement({K:"p",V:[{K:"strong",S1:a.text_line_1}]});
var T=e.createElement({K:"p",V:[{K:"span",U:"iv-promo-link",S1:a.text_line_2}]});if(h=a.text_line_3){P.push("iv-promo-website-card-cta-redesign");var X=e.createElement({K:"button",WW:["iv-promo-round-expand-icon","ytp-button"]});h=e.createElement({K:"button",WW:["iv-button","iv-promo-button"],V:[{K:"span",U:"iv-button-content",S1:h}]});var f=e.createElement({K:"div",U:"iv-promo-button-container"});f.appendChild(h);B&&Kx(e,e.EM(),B,e.annotation.id,a.session_data,void 0,r)}g.rr(e.S,"iv-click-target");
B&&Kx(e,e.S,B,e.annotation.id,a.session_data,void 0,r);break;case "playlist":case "video":y=e.createElement({K:"p",V:[{K:"span",S1:a.text_line_1}]}),T=e.createElement({K:"p",V:[{K:"strong",S1:a.text_line_2}]}),a.is_live&&(y=T,T=e.createElement({K:"span",WW:["yt-badge","iv-promo-badge-live"],S1:"LIVE NOW"})),g.rr(e.S,"iv-click-target"),B&&Kx(e,e.S,B,e.annotation.id,a.session_data,void 0,r),P.push("iv-promo-video")}y&&e.S.appendChild(y);T&&e.S.appendChild(T);e.D.appendChild(e.S);f&&e.D.appendChild(f);
r=e.createElement({K:"div",U:"iv-promo-actions"});e.T=e.createElement({K:"button",WW:["iv-promo-expand","ytp-button"]});e.T.title="Expand";e.context.S.listen(e.T,"click",function(A){$XB(e,5E3,A)});
r.appendChild(e.T);g.PQ(e.T,!1);e.context.S.listen(e.EM(),"mouseover",e.AV,e);e.context.S.listen(e.EM(),"mouseout",e.xD,e);e.context.S.listen(e.EM(),"touchend",function(A){$XB(e,5E3,A)});
e.B=e.createElement({K:"button",WW:["iv-promo-close","ytp-button"]});e.B.title="Close";e.context.S.listen(e.B,"click",e.annotation.style==="cta"&&a.text_line_3?e.mS:e.c$,e);r.appendChild(e.B);g.PD(e.EM(),P);c&&(g.G7(e.EM(),c),X&&c.appendChild(X));g.G7(e.EM(),e.D);g.G7(e.EM(),r)},$XB=function(e,a,r){r.stopPropagation();
WnG(e);l$a(e,a);e.S.focus()},LnM=function(e){e.isCollapsed||e.Y||e.L||(g.rr(e.EM(),"iv-promo-collapsed"),e.isCollapsed=!0,e.C.start())},WnG=function(e){e.C.stop();
e.isCollapsed&&(g.hi(e.EM(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),e.isCollapsed=!1,e.S&&e.S.removeAttribute("aria-hidden"),g.PQ(e.T,!1),g.PQ(e.B,!0))},l$a=function(e,a){e.L||(e.L=g.zQ(function(){YX8(this);
LnM(this)},a,e))},YX8=function(e){e.L&&(g.uq.clearTimeout(e.L),e.L=null)},wJN=function(e){this.W=e},f$b=function(e,a,r){a&&(r?T_(e,a.map(function(P){return g.Vm(P,r)})):T_(e,a))},T_=function(e,a,r,P){var B=1,h=void 0,c=-1;
if(r){var y=!1;h=function(){B--;B||y||(clearTimeout(c),y=!0,r())};
c=setTimeout(function(){y=!0;r()},1E3)}a=g.Z(a||[]);
for(var T=a.next();!T.done;T=a.next())T=T.value,B++,g.Lu(T,h);P&&(B++,P!==0&&e.W.sendVideoStatsEngageEvent(P,h))},pJV=function(e){g.Vn.call(this,e);
var a=this;this.HW=this.Y=!1;this.loadNumber=0;this.Z={};this.logger=new wJN(this.player);this.L=new g.Zc(this);this.C=this.D=null;this.events=new g.Zc(this);this.VP=this.N=this.S=null;this.oH=[];g.x(this,this.L);this.L.j(this.player,"onVideoAreaChange",function(){a.publish("onVideoAreaChange")});
this.L.j(this.player,"onHideControls",function(){a.publish("onHideControls")});
this.L.j(this.player,"onShowControls",function(){a.publish("onShowControls")});
this.L.j(this.player,"resize",function(P){a.publish("resize",P)});
this.L.j(this.player,"presentingplayerstatechange",function(P){a.publish("presentingplayerstatechange",P)});
this.subscribe("presentingplayerstatechange",this.TI,this);this.subscribe("resize",this.Fl,this);this.player.G().e1.subscribe("vast_info_card_add",this.zK,this);g.x(this,this.events);this.TQ=this.createElement({K:"div",U:"video-custom-annotations"});this.T=new g.v({K:"div",WW:["ytp-player-content","ytp-iv-player-content"]});g.x(this,this.T);g.MY(this.player,this.T.element,4);this.T.hide();this.B=new g.v({K:"div",WW:["ytp-iv-video-content"]});g.x(this,this.B);e=this.createElement({K:"div",U:"video-annotations"});
e.appendChild(this.TQ);this.B.element.appendChild(e);this.VB()&&this.load();var r=this.createElement({K:"style"});(g.h5("HEAD")[0]||document.body).appendChild(r);this.addOnDisposeCallback(function(){g.t5(r)});
if(e=r.sheet)e.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),e.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),e.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),e.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),e.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),e.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),e.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),e.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),e.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),e.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},i0V=function(e){e=e.createElement({K:"div",
WW:["annotation","annotation-type-custom"]});g.PQ(e,!1);return e},zka=function(e,a){a=!a.isCued()&&!g.S(a,1024);
e.T.Nr(a);e.B.Nr(a)},NNG=function(e,a,r){e.Y=!0;
e.C=g.ge(a,r)},xXZ=function(e,a){for(var r={},P=g.Z(a.attributes),B=P.next();!B.done;B=P.next())B=B.value,r[B.name]=B.nodeValue;
for(P=0;P<a.childNodes.length;P++)if(B=a.childNodes[P],g.hw(B)&&B.nodeType==1){if(r[B.tagName])var h=r[B.tagName];else if(B.tagName==="data"){B.childNodes.length>0&&(h=B.childNodes[0].nodeValue,r[B.tagName]=typeof h==="string"?h.trim():h);continue}else h=[],r[B.tagName]=h;B&&B.tagName==="TEXT"?B.childNodes.length===1&&B.childNodes[0].nodeType===3?h.push(B.childNodes[0].nodeValue):h.push(""):B&&h.push(xXZ(e,B))}return r},vLl=function(e){var a=e.player.getVideoData();
if(a.XM){var r=e.player.G().e1.get(a.videoId);if(r){var P={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(B,h,c){B=e.loadNumber;h=a.videoId;e.loaded&&e.loadNumber===B&&e.player.getVideoData().videoId===h&&(c=g.yU(c)&&c.responseXML?c.responseXML:null)&&I$G(e,c)}};
g.Ml()&&(P.onFinish=H0w(e,P.onFinish));P.postParams={ic_only:"1"};qXl(P,r);e.Y=!0;g.ge(a.XM,P)}}},qXl=function(e,a){e.method="POST";
e.postParams=e.postParams||{};a.k0&&(e.postParams.ic_coll=a.k0);a.Wa&&(e.postParams.ic_xml=a.Wa);a.hE&&(e.postParams.ic_track=a.hE)},RkB=function(e){var a=new g.v({K:"div"});
g.PQ(a.element,!1);var r=new oLZ(e.player,a.element,XY(e));g.x(r,a);a.Kf(e.T.element);r.N9();return r},s45=function(e,a){var r,P;
if(a=(r=a.getWatchNextResponse())==null?void 0:(P=r.cards)==null?void 0:P.cardCollectionRenderer)e.HW=!0,SXG(e,a),a.headerText&&e.VP&&(r=g.yd(a.headerText),e.player.X("player_tooltip_data_title_killswitch")?e.VP.setAttribute("title",r):e.VP.setAttribute("data-tooltip-title",r))},XY=function(e){if(!e.N){var a=new Vya(e);
g.x(e,a);var r=new g.CX(e);g.x(e,r);e.N=new DX9(a,r,e.player.G(),e.player.getVideoData(),e.logger,e.player,e.L5)}return e.N},I$G=function(e,a){var r=!1,P=a.getElementsByTagName("annotations");
if(P&&!(P.length<1)&&(P=P[0].getAttribute("itct"))){var B=g.bs();if(B){var h=g.Er();h&&g.s7(g.N9)(void 0,B,h,[g.C4(P)])}}a=a.getElementsByTagName("annotation");for(P=0;P<a.length;P++){h=xXZ(e,a[P]);B=null;try{if(h){var c=h.id,y=/.+/;var T=typeof c==="string"&&y!=null&&c!=null&&c.match(y)?c:"";var X=SJ(h.type,mXV),f=SJ(h.style,FnB),A=vjG(h.data),U=A.length!==0?JSON.parse(A):{};var C=h.action;h=MyN;if(C==null)var G=null;else if(g.BB(C)){y=[];for(var O=g.Z(C),d=O.next();!d.done;d=O.next()){var W=h(d.value);
W&&y.push(W)}G=y}else{var V=h(C);G=V?[V]:[]}B=T&&X?new jUa(T,X,f,G,U):null}else B=null}catch(cI){}if(B)if(B.type==="branding"||B.type==="promotion"){h=e;y=B;var L=i0V(h),z=null;switch(y.type){case "branding":if(h.player.G().kh)break;h.player.X("web_player_overlay_positioned_layout")?(L.setAttribute("data-overlay-order","11"),h.player.Pe(L,4,!0)):h.T.element.appendChild(L);z=new yo(L,XY(h),y);break;case "promotion":g.MY(h.player,L,4),z=new V5N(L,XY(h),y)}z&&z.N9();if(h=z)g.x(e,h),e.Z[B.id]=h}else if(B.type===
"card"||B.type==="drawer"){e.S||(e.S=RkB(e),g.x(e,e.S));if(B.type==="card"){L=e.S;var q=(r=B)&&r.data&&r.data.card_type;B=r.data;if(q)switch(h=B.tracking||{},h={Ia:h.impression,click:h.click,close:h.close,aK:h.teaser_impression,Zb:h.teaser_click},y=B.tracking_params||{},z=null,q){case "collaborator":r={id:r.id,timestamp:B.timestamp||0,type:B.card_type,teaserText:B.teaser_text,teaserDurationMs:B.teaser_duration_ms,startMs:B.start_ms,autoOpen:B.auto_open||!1,sessionData:B.session_data||{},sponsored:B.sponsored||
!1,Bo:h,jV:y.card?g.C4(y.card):null,FJ:y.teaser?g.C4(y.teaser):null,uc:y.icon?g.C4(y.icon):null,channelId:B.channel_id,customMessage:B.custom_message?B.custom_message:null,profileImageUrl:B.image_url,title:B.title,metaInfo:B.meta_info,url:mC({pause_on_navigation:B.pause_on_navigation,target:B.target||"new",value:B.url}),onClickCommand:null};BY(L,r);break;case "playlist":r={id:r.id,timestamp:B.timestamp||0,type:B.card_type,teaserText:B.teaser_text,teaserDurationMs:B.teaser_duration_ms,startMs:B.start_ms,
autoOpen:B.auto_open||!1,sessionData:B.session_data||{},sponsored:B.sponsored||!1,Bo:h,jV:y.card?g.C4(y.card):null,FJ:y.teaser?g.C4(y.teaser):null,uc:y.icon?g.C4(y.icon):null,aP:B.image_url,playlistVideoCount:B.playlist_video_count,customMessage:B.custom_message?B.custom_message:null,title:B.title,metaInfo:B.meta_info,url:mC({pause_on_navigation:B.pause_on_navigation,target:B.target||"new",value:B.url}),onClickCommand:null};BY(L,r);break;case "productListing":B.signin_url&&(z=mC({target:"current",
value:B.signin_url}));q=[];for(var M=B.offers||[],m=0;m<M.length;m++)q.push(new P5N(g.lF(M[m].merchant),g.lF(M[m].price)));r={id:r.id,timestamp:B.timestamp||0,type:B.card_type,teaserText:B.teaser_text,teaserDurationMs:B.teaser_duration_ms,startMs:B.start_ms,autoOpen:B.auto_open||!1,sessionData:B.session_data||{},sponsored:B.sponsored||!1,Bo:h,jV:y.card?g.C4(y.card):null,FJ:y.teaser?g.C4(y.teaser):null,uc:y.icon?g.C4(y.icon):null,imageUrl:B.image_url,displayDomain:B.display_domain?B.display_domain:
null,showLinkIcon:!!B.show_link_icon,Q$:B.button_icon_url?B.button_icon_url:null,title:B.title,customMessage:B.custom_message?B.custom_message:null,url:mC({pause_on_navigation:B.pause_on_navigation,target:B.target||"new",value:B.url}),Iqm:z,LCo:B.signin_title?B.signin_title:void 0,OiW:B.signin_message?B.signin_message:void 0,offers:q,onClickCommand:null};BY(L,r);break;case "simple":r={id:r.id,timestamp:B.timestamp||0,type:B.card_type,teaserText:B.teaser_text,teaserDurationMs:B.teaser_duration_ms,
startMs:B.start_ms,autoOpen:B.auto_open||!1,sessionData:B.session_data||{},sponsored:B.sponsored||!1,Bo:h,jV:y.card?g.C4(y.card):null,FJ:y.teaser?g.C4(y.teaser):null,uc:y.icon?g.C4(y.icon):null,imageUrl:B.image_url,displayDomain:B.display_domain?B.display_domain:null,showLinkIcon:!!B.show_link_icon,Q$:B.button_icon_url?B.button_icon_url:null,title:B.title,customMessage:B.custom_message?B.custom_message:null,url:mC({pause_on_navigation:B.pause_on_navigation,target:B.target||"new",value:B.url}),onClickCommand:null};
BY(L,r);break;case "video":r={id:r.id,timestamp:B.timestamp||0,type:B.card_type,teaserText:B.teaser_text,teaserDurationMs:B.teaser_duration_ms,startMs:B.start_ms,autoOpen:B.auto_open||!1,sessionData:B.session_data||{},sponsored:B.sponsored||!1,Bo:h,jV:y.card?g.C4(y.card):null,FJ:y.teaser?g.C4(y.teaser):null,uc:y.icon?g.C4(y.icon):null,aP:B.image_url,videoDuration:B.video_duration||null,customMessage:B.custom_message?B.custom_message:null,title:B.title,metaInfo:B.meta_info,isLiveNow:!!B.is_live_now,
url:mC({pause_on_navigation:B.pause_on_navigation,target:B.target||"new",value:B.url}),onClickCommand:null},BY(L,r)}}else nLw(e.S,B);r=!0}}r&&(Wl(e.player),e.Fl())},SXG=function(e,a){var r=!1;
e.S||(e.S=RkB(e),g.x(e,e.S));for(var P=g.Z(a.cards||[]),B=P.next();!B.done;B=P.next())B=B.value,B.cardRenderer&&(yqB(e.S,B.cardRenderer),r=!0);if(r){var h;(h=e.player.getVideoData())!=null&&g.en(h)||(r=e.S,P=a.headerText?g.yd(a.headerText):"",g.ZF(r.bv,P),r.C&&(r.W.X("player_tooltip_data_title_killswitch")?r.C.setAttribute("title",P):r.C.setAttribute("data-tooltip-title",P)),r.context.videoData.eventId&&(r.eventId=r.context.videoData.eventId),r.Lf=a.trackingParams?g.C4(a.trackingParams):null,r.Y=
a.closeButton.infoCardIconRenderer.trackingParams?g.C4(a.closeButton.infoCardIconRenderer.trackingParams):null,r.uc=a.icon.infoCardIconRenderer.trackingParams?g.C4(a.icon.infoCardIconRenderer.trackingParams):null,e.Fl());Wl(e.player)}},M5M=function(e,a,r,P,B){if(!e.player.G().kh){var h=[];
a.navigationEndpoint&&g.H(a.navigationEndpoint,g.sT)&&g.H(a.navigationEndpoint,g.sT).browseId&&h.push(new sUl("openUrl","click",new RAl("/channel/"+g.H(a.navigationEndpoint,g.sT).browseId,"new",!0,!0)));var c=a.watermark.thumbnails[0];P={channel_name:a.channelName,end_ms:a.endTimeMs,image_height:c.height,image_type:1,image_url:c.url,image_width:c.width,is_mobile:!1,session_data:{annotation_id:r,ei:B,feature:"iv",itct:a.trackingParams,src_vid:P},start_ms:a.startTimeMs};if(a.subscribeButton&&g.H(a.subscribeButton,
g.mR)){P.channel_id=g.H(a.subscribeButton,g.mR).channelId;var y;a=g.H(a.subscribeButton,g.mR);c=B=null;a.subscribed?(a.subscriberCountWithUnsubscribeText&&(B=g.yd(a.subscriberCountWithUnsubscribeText)),a.subscriberCountText&&(c=g.yd(a.subscriberCountText))):(a.subscriberCountText&&(B=g.yd(a.subscriberCountText)),a.subscriberCountWithSubscribeText&&(c=g.yd(a.subscriberCountWithSubscribeText)));var T,X=((T=g.H((y=a.signInEndpoint)==null?void 0:y.commandMetadata,g.d0))==null?void 0:T.url)||"";y={subscribeText:g.yd(a.unsubscribedButtonText),
subscribeCount:B||"",unsubscribeText:g.yd(a.subscribedButtonText),unsubscribeCount:c||"",enabled:a.enabled||!1,classic:!1,subscribed:a.subscribed||!1,feature:"iv",signInUrl:X};P.standalone_subscribe_button_data=y}h=new jUa(r,"branding","branding",h,P);y=i0V(e);e.player.X("web_player_overlay_positioned_layout")?(y.setAttribute("data-overlay-order","11"),e.player.Pe(y,4,!0)):e.T.element.appendChild(y);h=new yo(y,XY(e),h);h.N9();g.x(h,h);e.Z[r]=h}},H0w=function(e,a){return function(){var r=g.xN.apply(0,
arguments);
e.wP()||e.oH.push(g.i9.xL(function(){a.apply(null,g.UO(r))}))}},j4B=function(e){return e==="annotation-editor"||e==="live-dashboard"};
g.Hx.prototype.Qd=g.BI(39,function(e,a){var r=g.xp(this.eO());r&&r.Qd(e,a)});
var Lx={},Yt=null;g.UG(px,g.oc);g.E=px.prototype;g.E.getDuration=function(){return this.duration};
g.E.play=function(e){if(e||this.S==0)this.progress=0,this.coords=this.T;else if(this.isPlaying())return!1;wg(this);this.startTime=e=g.f5();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.L=this.startTime;this.progress||this.cU();this.XD("play");this.isPaused()&&this.XD("resume");this.S=1;var a=g.oZ(this);a in Lx||(Lx[a]=this);gjB();ZUb(this,e);return!0};
g.E.stop=function(e){wg(this);this.S=0;e&&(this.progress=1);OUN(this,this.progress);this.onStop();this.kX()};
g.E.pause=function(){this.isPlaying()&&(wg(this),this.S=-1,this.XD("pause"))};
g.E.RH=function(){this.S==0||this.stop(!1);this.XD("destroy");px.Tl.RH.call(this)};
g.E.destroy=function(){this.dispose()};
g.E.Nt=function(){this.XD("animate")};
g.E.XD=function(e){this.dispatchEvent(new kPb(e,this))};
g.UG(kPb,g.se);g.UG(iU,px);iU.prototype.B=function(){};
iU.prototype.Nt=function(){this.B();iU.Tl.Nt.call(this)};
iU.prototype.kX=function(){this.B();iU.Tl.kX.call(this)};
iU.prototype.cU=function(){this.B();iU.Tl.cU.call(this)};
g.UG(duN,iU);duN.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.b(Vya,g.N);g.E=Vya.prototype;g.E.listen=function(e,a,r,P){r=(0,g.yG)(r,P||this.T);e=g.Eu(e,a,r);this.S.push(e);return e};
g.E.EL=function(e,a,r,P){r=(0,g.yG)(r,P||this.T);e=bUa(e,a,r);this.S.push(e);return e};
g.E.Xo=function(e){g.bQ(e);g.k9(this.S,e)};
g.E.removeAll=function(){g.bQ(this.S);this.S.length=0};
g.E.RH=function(){this.removeAll();g.N.prototype.RH.call(this)};g.b(WTN,g.Vn);g.E=WTN.prototype;g.E.load=function(){g.Vn.prototype.load.call(this);if(!xt(this)){var e=g.Sly(this.player.getVideoData());e?(e=QUB(e,lQN(this)),IL(this,e,!1)):LTV(this)}};
g.E.unload=function(){IL(this,null);this.L&&(this.L.abort(),this.L=null);g.Vn.prototype.unload.call(this)};
g.E.i$=function(e,a){return xt(this)?e==="loadCustomEndscreenRenderer"?(e=QUB(a,"new"),IL(this,e),!0):null:null};
g.E.getOptions=function(){return xt(this)?["loadCustomEndscreenRenderer"]:[]};
g.E.VX=function(){if(this.endscreen&&this.endscreen.elements){var e=this.player.getVideoContentRect();if(e&&e.width!==0&&e.height!==0){var a=this.player.getPlayerSize();if(a&&a.width!==0&&a.height!==0){var r=e.width/e.height;var P=0;for(var B=-1,h=0;h<u9a.length;h++){var c=Math.abs(a.width-u9a[h]);if(B===-1||P>=c)B=h,P=c}P=Kn5[B];this.B&&g.vo(this.B.element,"outline-width",Math.max(a.width,a.height)+"px");for(a=0;a<this.endscreen.elements.length;++a)if(h=this.endscreen.elements[a].id,B=this.T[h],
c=this.Z[h],B&&c){var y=c.width*r/c.aspectRatio,T=Math.round(c.width*e.width);h=Math.round(y*e.height);var X=e.left+Math.round(c.left*e.width),f=e.top+Math.round(c.top*e.height);g.ab(B.element,T,h);g.j2(B.element,X,f);g.hi(B.element,eDV);T>256||h>256?g.rr(B.element,"ytp-ce-large-round"):T>96||h>96?g.rr(B.element,"ytp-ce-medium-round"):g.rr(B.element,"ytp-ce-small-round");g.hi(B.element,aKa);T=c.left+c.width/2;c=c.top+y/2;g.rr(B.element,T<=.5&&c<=.5?"ytp-ce-top-left-quad":T>.5&&c<=.5?"ytp-ce-top-right-quad":
T<=.5&&c>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.hi(B.element,Kn5);g.rr(B.element,P);(B=g.o8(document,"div","ytp-ce-expanding-overlay-body",B.element)[0])&&g.vo(B,"height",h+"px")}}}}};
g.E.onCueRangeEnter=function(e){if(this.endscreen)if(e.getId()==="ytp-ce-in-endscreen")RL(this,this.endscreen.impressionUrls),(e=g.bs())&&this.endscreen.visualElement&&g.ma(e,this.endscreen.visualElement),this.S&&(g.rr(this.S,"ytp-ce-element-show"),this.S.removeAttribute("aria-hidden"),this.player.BI()?g.rr(this.S,"ytp-ce-hide-button-lower"):g.BD(this.S,"ytp-ce-hide-button-lower"));else{e=e.getId().substring(15);var a=this.T[e],r=this.Z[e];g.rr(a.element,"ytp-ce-element-show");a.element.removeAttribute("aria-hidden");
a=this.player.getRootNode();g.rr(a,"ytp-ce-shown");RL(this,r.impressionUrls);(a=g.bs())&&g.ma(a,r.visualElement);this.player.G().Y&&this.player.qF("endscreenelementshown",e)}};
g.E.onCueRangeExit=function(e){if(e.getId()==="ytp-ce-in-endscreen")this.S&&(g.BD(this.S,"ytp-ce-element-show"),this.S.setAttribute("aria-hidden","true"));else{e=e.getId().substring(15);var a=this.T[e];g.BD(a.element,"ytp-ce-element-show");a.element.setAttribute("aria-hidden","true");a=this.player.getRootNode();g.BD(a,"ytp-ce-shown");this.player.G().Y&&this.player.qF("endscreenelementhidden",e)}};
g.E.wZH=function(e){var a=this;e.target===window&&(new g.vP(function(){for(var r=g.Z(Object.values(a.T)),P=r.next();!P.done;P=r.next())g.hi(P.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.E.Nr=function(e){for(var a=g.Z(Object.values(this.T)),r=a.next();!r.done;r=a.next())r=r.value,e?r.element.setAttribute("hidden",""):r.element.removeAttribute("hidden")};
g.E.y1M=function(e){this.S&&this.player.getRootNode().removeChild(this.S);e&&(g.rr(e,"ytp-ce-hide-button-container"),this.S=e,g.MY(this.player,this.S,4))};
var u9a=[346,426,470,506,570,640,853,1280,1920],Kn5="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),aKa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],eDV=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var SbB={R5m:"current",AOd:"new"};var muZ={CLOSE:"close",qeF:"openUrl",SUBSCRIBE:"subscribe"},FT5={JHP:"click",CLOSE:"close",Tcz:"hidden",m2F:"rollOut",h7$:"rollOver",FIQ:"shown"};jUa.prototype.ju=function(){var e=u6l(this,function(a){return a.type==="openUrl"&&a.url!=null});
return e?e.url:null};
var FnB={VX$:"anchored",PX:"branding",CHANNEL:"channel",poF:"cta",OhP:"highlightText",r4$:"label",PLAYLIST:"playlist",POPUP:"popup",uDW:"speech",SUBSCRIBE:"subscribe",LQ$:"title",VIDEO:"video",MQo:"website"},mXV={PX:"branding",fnm:"card",e5H:"drawer",gPW:"highlight",Kd$:"marker",LIH:"promotion",TEXT:"text",Dj$:"widget"};g.b(uU,g.N);g.E=uU.prototype;g.E.addCueRange=function(e,a,r,P,B){e=new g.v_(e,a,{id:r,namespace:"annotations_module"});P&&this.GQ.set(e,P);B&&this.ym.set(e,B);this.context.W.Ji([e],1)};
g.E.N9=function(){this.context.T.subscribe("resize",this.JY,this)};
g.E.EM=function(){return this.element};
g.E.i8=function(e,a,r,P,B,h){if(this.rP)return!1;h&&(h.stopPropagation(),h.preventDefault());this.navigate(e,r,P,B);return!1};
g.E.show=function(){};
g.E.hide=function(){};
g.E.destroy=function(){g.t5(this.EM())};
g.E.JY=function(){};
g.E.navigate=function(e,a,r,P){var B=this,h=sz(e);if(h){var c=hk9(h,e.target),y=function(){e.S&&B.context.W.pauseVideo();var T=B.context.videoData.nB||!1,X=g.KG(h||"");T&&X&&(X.v||X.list)?B.context.W.nY(X.v,a,X.list,!1):g.xg(h||"",c==="current"?"_top":void 0,a)};
c==="new"&&(y(),y=null);T_(this.context.logger,r,y,P);BNV(h)||(r=g.bs(),P=a.itct,r&&P&&g.js(r,g.C4(P)))}};
g.E.RH=function(){this.GQ.clear();this.ym.clear();g.N.prototype.RH.call(this)};
g.E.createElement=function(e){e=new g.v(e);g.x(this,e);return e.element};g.b(oLZ,uU);g.E=oLZ.prototype;g.E.zm=function(){this.oH&&BY(this,this.oH)};
g.E.isAvailable=function(){var e;if(e=!!this.cards.length)(e=this.W.getRootNode())?(e=g.rF(e),e=173<e.width&&173<e.height):e=!1;return e};
g.E.JY=function(){var e=this.isAvailable();g.PQ(this.EM(),e);g.cD(this.context.W.getRootNode(),g.to.IV_DRAWER_ENABLED,e);Wl(this.W)};
g.E.destroy=function(){this.W.Qd(!1);try{this.W.getRootNode().removeChild(this.L)}catch(e){}g.u4(this.HW);g.du(this.XM);this.Uo&&this.Uo.dispose();this.Z&&this.Z.dispose();uU.prototype.destroy.call(this)};
g.E.Qs=function(){var e=this;this.context.S.listen(g.nO("iv-drawer-close-button",this.L),"click",this.f3,this);this.context.S.listen(this.T,"touchend",function(){e.Eo.start()});
this.context.S.listen(this.T,"scroll",this.ol,this);this.context.T.subscribe("onHideControls",function(){e.e1=!0});
this.context.T.subscribe("onShowControls",function(){e.e1=!1});
this.context.T.subscribe("onVideoAreaChange",function(){e.e1=g.ac(e.W.getRootNode(),"ytp-autohide")});
this.HW.push(g.jA("iv-button-shown",this.VE,this));this.HW.push(g.jA("iv-button-hidden",this.kz,this));UXB(this)};
g.E.findLastIndex=function(e){if(this.cards.length===0)return 0;var a=g.gb(this.cards,function(r){return e.PG.startMs>r.PG.startMs||e.PG.startMs===r.PG.startMs&&e.PG.timestamp>=r.PG.timestamp?!0:!1});
return a===-1?0:a+1};
g.E.f3=function(){if(this.B){T_(this.context.logger,o3(this).Bo.close);var e=g.bs();e&&this.Y&&g.js(e,this.Y);r$(this)}};
g.E.ol=function(){g.cD(this.L,"iv-drawer-scrolled",this.T.scrollTop>0)};
g.E.VE=function(){var e=g.bs(),a=o3(this);a=a?a.uc:this.uc;e&&a&&g.F_(e,[a])};
g.E.kz=function(){var e=g.bs(),a=o3(this);a=a?a.uc:this.uc;e&&a&&g.M9(e,[a])};
g.E.R0=function(){var e=o3(this);T_(this.context.logger,e.Bo.aK);var a=g.bs();if(a&&e)if(this.W.X("web_infocards_teaser_show_logging_fix")){var r=[];e.FJ&&r.push(e.FJ);e.uc&&r.push(e.uc);r.length>0&&g.F_(a,r)}else g.F_(a,[e.FJ,e.uc])};
g.E.MR=function(){var e=g.bs(),a=o3(this);e&&a&&g.M9(e,[a.FJ])};
g.E.pw=function(e){var a=o3(this),r=g.bs();this.S?e?(e=this.context.logger,T_(e,a.Bo.Zb),e.W.sendVideoStatsEngageEvent(4,void 0),r&&a.FJ&&g.js(r,a.FJ)):(e=this.context.logger,T_(e,a.Bo.Zb),e.W.sendVideoStatsEngageEvent(4,void 0),r&&a.uc&&g.js(r,a.uc)):(e=this.context.logger,T_(e,a.Bo.Zb),e.W.sendVideoStatsEngageEvent(4,void 0),r&&this.uc&&g.js(r,this.uc))};g.b(nq,uU);nq.prototype.N9=function(){uU.prototype.N9.call(this);Z0G(this)};
nq.prototype.show=function(){uU.prototype.show.call(this);var e=g.bs(),a=this.annotation.data;e&&a&&(a=a.session_data)&&g.F_(e,[g.C4(a.itct)])};
nq.prototype.hide=function(){uU.prototype.hide.call(this);var e=g.bs(),a=this.annotation.data;e&&a&&(a=a.session_data)&&g.M9(e,[g.C4(a.itct)])};g.b(yo,nq);
yo.prototype.show=function(){if(!this.isActive){nq.prototype.show.call(this);if(!this.D){g.rr(this.EM(),"iv-branding");var e=this.annotation.data;this.T=this.createElement({K:"img",WW:["branding-img","iv-click-target"],J:{"aria-label":"Channel watermark",src:e.image_url,width:e.image_width,height:e.image_height}});g.PQ(this.T,!1);var a=this.createElement({K:"button",WW:["branding-img-container","ytp-button"]});a.appendChild(this.T);this.EM().appendChild(a);var r=this.annotation.ju();r&&Kx(this,a,
r,this.annotation.id,e.session_data);this.context.W.X("disable_branding_context")||JqB(this,e);this.D=!0}g.PQ(this.EM(),!0);this.isActive=!0;if(this.T){try{O0w(this,this.T)}catch(P){}g.rr(this.context.W.getRootNode(),"ytp-branding-shown");this.context.W.getRootNode().style.setProperty("--branding-image-width",this.T.getAttribute("width")+"px")}}};
yo.prototype.hide=function(){this.isActive&&(nq.prototype.hide.call(this),g.PQ(this.EM(),!1),this.isActive=!1,g.BD(this.context.W.getRootNode(),"ytp-branding-shown"))};
yo.prototype.destroy=function(){this.S&&(this.S.dispose(),this.S=null);g.BD(this.context.W.getRootNode(),"ytp-branding-shown");nq.prototype.destroy.call(this)};g.b(V5N,nq);g.E=V5N.prototype;g.E.show=function(){this.isActive||(nq.prototype.show.call(this),this.N||(Q4b(this),this.N=!0),g.PQ(this.EM(),!0),g.zQ(function(){g.BD(this.EM(),"iv-promo-inactive")},100,this),this.EM().removeAttribute("aria-hidden"),this.isActive=!0,YX8(this),WnG(this),l$a(this,this.Z))};
g.E.hide=function(){this.isActive&&(g.rr(this.EM(),"iv-promo-inactive"),this.isActive=!1,this.EM().setAttribute("aria-hidden","true"))};
g.E.i8=function(e,a,r,P,B,h){return this.isCollapsed?!1:nq.prototype.i8.call(this,e,a,r,P,B,h)};
g.E.AV=function(e){this.Y=!0;$XB(this,500,e)};
g.E.xD=function(){this.Y=!1;LnM(this)};
g.E.c$=function(e){e.stopPropagation();this.hide()};
g.E.mS=function(e){e.stopPropagation();YX8(this);this.isCollapsed=!0;g.rr(this.EM(),"iv-promo-collapsed-no-delay");this.C.start()};
g.E.destroy=function(){this.C.dispose();nq.prototype.destroy.call(this)};g.b(pJV,g.Vn);g.E=pJV.prototype;g.E.i$=function(e,a){if(!j4B(this.player.G().playerStyle))return null;switch(e){case "loadCustomAnnotationsXml":return(e=g.KS(a))&&I$G(this,e),!0;case "removeCustomAnnotationById":return a&&this.S&&(XJw(this.S,a),Wl(this.player)),!0}return null};
g.E.getOptions=function(){return j4B(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.E.VB=function(){var e=this.player.G(),a=this.player.getVideoData(),r=e.annotationsLoadPolicy||a.annotationsLoadPolicy;return a.nB||this.player.isMutedByEmbedsMutedAutoplay()?!1:r===1&&!a.A$||e.e1.get(a.videoId)||g.ak(a)||g.rC(a)?!0:!1};
g.E.Fl=function(){if(this.B){var e=this.player.MF().getVideoContentRect(!0);g.ab(this.B.element,e.width,e.height);g.j2(this.B.element,e.left,e.top)}if(this.S){var a=this.player.jZ();e=this.S;a=a.width;g.cD(e.L,"iv-drawer-small",a<=426);g.cD(e.L,"iv-drawer-big",a>=1280)}};
g.E.TI=function(e){zka(this,e.state);g.S(e.state,2)&&(this.BI()&&this.DI()&&this.player.getPresentingPlayerType()!==2&&this.DC(!1),this.Qd(!1))};
g.E.load=function(){function e(c){var y=a.loadNumber;a.C=null;a.loaded&&a.loadNumber===y&&a.player.getVideoData().videoId===P&&(c=g.yU(c)&&c.responseXML?c.responseXML:null)&&(I$G(a,c),g.rr(a.player.getRootNode(),"iv-module-loaded"))}
var a=this;g.Vn.prototype.load.call(this);zka(this,this.player.getPlayerStateObject());this.loadNumber++;var r=this.player.getVideoData(),P=r.videoId;g.Ml()&&(e=H0w(this,e));var B={format:"XML",onFinish:e,onError:function(){a.C=null},
urlParams:{}};r.isPharma&&(B.urlParams.pharma="1");B.method="POST";B.withCredentials=!0;var h=this.player.G().e1.get(P);h&&qXl(B,h);h=h&&(h.Wa||h.k0);if(!r.Mo||h)r.XM?NNG(this,r.XM,B):(this.D=function(){if(!a.Y)a.onVideoDataChange(B);var c=a.player.getVideoData();(c==null?0:g.en(c))&&!a.HW&&s45(a,c)},this.player.addEventListener("videodatachange",this.D));
g.MY(this.player,this.B.element,4);this.Fl();(h=g.ak(r))&&SXG(this,h);(h=g.rC(r))&&h.featuredChannel&&M5M(this,h.featuredChannel,h.annotationId||"branding",r.videoId||null,r.eventId||null);this.VP=g.nO("ytp-cards-button",this.player.getRootNode());g.en(r)&&s45(this,r)};
g.E.onVideoDataChange=function(e){var a=this.player.getVideoData();a.XM&&NNG(this,a.XM,e)};
g.E.unload=function(){this.player.Ai("annotations_module");for(var e=g.Z(Object.keys(this.Z)),a=e.next();!a.done;a=e.next())this.Z[a.value].destroy();this.N=null;this.S&&(this.S.destroy(),this.S=null,Wl(this.player));this.Y=!1;this.C&&(this.C.abort(),this.C=null);this.HW=!1;this.Z={};this.T.hide();g.Vn.prototype.unload.call(this);this.B.detach();this.D&&(this.player.removeEventListener("videodatachange",this.D),this.D=null)};
g.E.zK=function(e){e===this.player.getVideoData().videoId&&(this.loaded?vLl(this):this.load())};
g.E.BI=function(){var e;return((e=this.S)==null?void 0:e.isAvailable())||this.HW};
g.E.DI=function(){return!!this.S&&this.S.B};
g.E.DC=function(e,a,r){a=a===void 0?!1:a;this.BI();this.S&&(e?r?a3(this.S,r,a):a3(this.S,"YOUTUBE_DRAWER_AUTO_OPEN",a):r$(this.S))};
g.E.Qd=function(e,a){this.player.publish(e?"cardsteasershow":"cardsteaserhide",a)};
g.E.RH=function(){this.player.G().e1.unsubscribe("vast_info_card_add",this.zK,this);g.BD(this.player.getRootNode(),g.to.IV_DRAWER_OPEN);for(var e=this.oH,a=g.i9,r=0,P=e.length;r<P;r++)a.OQ(e[r]);this.oH.length=0;g.Vn.prototype.RH.call(this)};
g.E.createElement=function(e){e=new g.v(e);g.x(this,e);return e.element};g.DD("annotations_module",pJV);g.DD("creatorendscreen",WTN);})(_yt_player);
