(function(g){var window=this;'use strict';var teB=function(e){e.publish("autonavvisibility")},g3a=function(e,a){e.qF("onAutonavCoundownStarted",a)},Z6G=function(e){var a,r,P;
return e==null?void 0:(a=e.playerOverlays)==null?void 0:(r=a.playerOverlayRenderer)==null?void 0:(P=r.autoplay)==null?void 0:P.playerOverlayAutoplayRenderer},oC=function(e){var a=e.G(),r=a.L;
g.v.call(this,{K:"a",U:"ytp-autonav-suggestion-card",J:{href:"{{url}}",target:r?a.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{K:"div",WW:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],J:{style:"{{background}}"},V:[{K:"div",J:{"aria-label":"{{timestamp}}"},WW:["ytp-autonav-timestamp"],S1:"{{duration}}"},{K:"div",WW:["ytp-autonav-live-stamp"],S1:"Live"},{K:"div",
WW:["ytp-autonav-upcoming-stamp"],S1:"Upcoming"},{K:"div",U:"ytp-autonav-list-overlay",V:[{K:"div",U:"ytp-autonav-mix-text",S1:"Mix"},{K:"div",U:"ytp-autonav-mix-icon"}]}]},{K:"div",WW:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],S1:"{{title}}"},{K:"div",WW:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],S1:"{{author}}"},{K:"div",WW:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],S1:"{{views_and_publish_time}}"}]});this.W=e;this.suggestion=
null;this.S=r;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},nb=function(e,a){a=a===void 0?!1:a;
g.v.call(this,{K:"div",U:"ytp-autonav-endscreen-countdown-overlay"});var r=this;this.D=a;this.cancelCommand=this.Z=void 0;this.B=0;this.container=new g.v({K:"div",U:"ytp-autonav-endscreen-countdown-container"});g.x(this,this.container);this.container.Kf(this.element);a=e.G();var P=a.L;this.W=e;this.suggestion=null;this.onVideoDataChange("newdata",this.W.getVideoData());this.j(e,"videodatachange",this.onVideoDataChange);this.S=new g.v({K:"div",U:"ytp-autonav-endscreen-upnext-container",J:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{K:"div",U:"ytp-autonav-endscreen-upnext-header"},{K:"div",U:"ytp-autonav-endscreen-upnext-alternative-header",S1:"{{autoplayAlternativeHeader}}"},{K:"a",U:"ytp-autonav-endscreen-link-container",J:{href:"{{url}}",target:P?a.N:""},V:[{K:"div",U:"ytp-autonav-endscreen-upnext-thumbnail",J:{style:"{{background}}"},V:[{K:"div",J:{"aria-label":"{{timestamp}}"},WW:["ytp-autonav-timestamp"],
S1:"{{duration}}"},{K:"div",WW:["ytp-autonav-live-stamp"],S1:"Live"},{K:"div",WW:["ytp-autonav-upcoming-stamp"],S1:"Upcoming"}]},{K:"div",U:"ytp-autonav-endscreen-video-info",V:[{K:"div",U:"ytp-autonav-endscreen-premium-badge"},{K:"div",U:"ytp-autonav-endscreen-upnext-title",S1:"{{title}}"},{K:"div",U:"ytp-autonav-endscreen-upnext-author",S1:"{{author}}"},{K:"div",U:"ytp-autonav-view-and-date",S1:"{{views_and_publish_time}}"},{K:"div",U:"ytp-autonav-author-and-view",S1:"{{author_and_views}}"}]}]}]});
g.x(this,this.S);this.S.Kf(this.container.element);P||this.j(this.S.BW("ytp-autonav-endscreen-link-container"),"click",this.Zu);this.W.createClientVe(this.container.element,this,115127);this.W.createClientVe(this.S.BW("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.v({K:"div",U:"ytp-autonav-overlay"});g.x(this,this.overlay);this.overlay.Kf(this.container.element);this.T=new g.v({K:"div",U:"ytp-autonav-endscreen-button-container"});g.x(this,this.T);this.T.Kf(this.container.element);
this.cancelButton=new g.v({K:"button",WW:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",a.X("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],J:{"aria-label":"Cancel autoplay"},S1:"Cancel"});g.x(this,this.cancelButton);this.cancelButton.Kf(this.T.element);this.cancelButton.listen("click",this.Kw,this);this.W.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.v({K:"a",WW:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
a.X("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],J:{href:"{{url}}",role:"button","aria-label":"Play next video"},S1:"Play Now"});g.x(this,this.playButton);this.playButton.Kf(this.T.element);this.playButton.listen("click",this.Zu,this);this.W.createServerVe(this.playButton.element,this.playButton,!0);(a=this.W.getVideoData())&&O6N(this,a);this.L=new g.vP(function(){kTV(r)},500);
g.x(this,this.L);this.l_();this.j(e,"autonavvisibility",this.l_);this.W.X("web_autonav_color_transition")&&(this.j(e,"autonavchange",this.EV),this.j(e,"onAutonavCoundownStarted",this.sHM))},yh=function(e){var a=e.W.jZ(!0,e.W.isFullscreen());
g.cD(e.container.element,"ytp-autonav-endscreen-small-mode",e.tA(a));g.cD(e.container.element,"ytp-autonav-endscreen-is-premium",!!e.suggestion&&!!e.suggestion.uIM);g.cD(e.W.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!e.W.eK());g.cD(e.W.getRootNode(),"countdown-running",e.UQ());g.cD(e.container.element,"ytp-player-content",e.W.eK());g.vo(e.overlay.element,{width:a.width+"px"});if(!e.UQ()){e.W.eK()?df9(e,Math.round(JVG(e)/1E3)):df9(e);a=!!e.suggestion&&!!e.suggestion.Mg;var r=e.W.eK()||
!a;g.cD(e.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!r&&a);g.cD(e.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",r&&!a);e.T.Nr(e.W.eK());g.cD(e.element,"ytp-enable-w2w-color-transitions",Dfl(e))}},kTV=function(e){var a=JVG(e),r=Math,P=r.min;
var B=e.B?Date.now()-e.B:0;r=P.call(r,B,a);df9(e,Math.ceil((a-r)/1E3));a-r<=500&&e.UQ()?e.select(!0):e.UQ()&&e.L.start()},JVG=function(e){if(e.W.isFullscreen()){var a;
e=(a=e.W.getVideoData())==null?void 0:a.E$;return e===-1||e===void 0?8E3:e}return e.W.Zq()>=0?e.W.Zq():g.eS(e.W.G().experiments,"autoplay_time")||1E4},O6N=function(e,a){a=a.getWatchNextResponse();
var r,P;a=(r=Z6G(a))==null?void 0:(P=r.nextButton)==null?void 0:P.buttonRenderer;e.Z=a==null?void 0:a.navigationEndpoint;r=a==null?void 0:a.trackingParams;e.playButton&&r&&e.W.setTrackingParams(e.playButton.element,r)},Dfl=function(e){var a;
return!((a=e.W.getVideoData())==null||!a.watchToWatchTransitionRenderer)},df9=function(e,a){a=a===void 0?-1:a;
e=e.S.BW("ytp-autonav-endscreen-upnext-header");g.E9(e);if(a>=0){a=String(a);var r="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],P="Up next in $SECONDS".indexOf(r);if(P>=0){e.appendChild(g.CO("Up next in $SECONDS".slice(0,P)));var B=g.U9("span");g.eG(B,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ZF(B,a);e.appendChild(B);e.appendChild(g.CO("Up next in $SECONDS".slice(P+r.length)));return}}g.ZF(e,"Up next")},Tv=function(e,a){g.v.call(this,{K:"div",
WW:["html5-endscreen","ytp-player-content",a||"base-endscreen"]});this.created=!1;this.player=e},XG=function(e){g.v.call(this,{K:"div",
WW:["ytp-upnext","ytp-player-content"],J:{"aria-label":"{{aria_label}}"},V:[{K:"div",U:"ytp-cued-thumbnail-overlay-image",J:{style:"{{background}}"}},{K:"span",U:"ytp-upnext-top",V:[{K:"span",U:"ytp-upnext-header",S1:"Up Next"},{K:"span",U:"ytp-upnext-title",S1:"{{title}}"},{K:"span",U:"ytp-upnext-author",S1:"{{author}}"}]},{K:"a",U:"ytp-upnext-autoplay-icon",J:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{K:"svg",J:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{K:"circle",U:"ytp-svg-autoplay-circle",J:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{K:"circle",U:"ytp-svg-autoplay-ring",J:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{K:"path",U:"ytp-svg-fill",J:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{K:"span",U:"ytp-upnext-bottom",V:[{K:"span",U:"ytp-upnext-cancel"},{K:"span",U:"ytp-upnext-paused",
S1:"Autoplay is paused"}]}]});this.api=e;this.cancelButton=null;this.Z=this.BW("ytp-svg-autoplay-ring");this.B=this.notification=this.S=this.suggestion=null;this.L=new g.vP(this.i4,5E3,this);this.T=0;var a=this.BW("ytp-upnext-cancel");this.cancelButton=new g.v({K:"button",WW:["ytp-upnext-cancel-button","ytp-button"],J:{tabindex:"0","aria-label":"Cancel autoplay"},S1:"Cancel"});g.x(this,this.cancelButton);this.cancelButton.listen("click",this.WF,this);this.cancelButton.Kf(a);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.x(this,this.L);this.api.createClientVe(this.element,this,18788);a=this.BW("ytp-upnext-autoplay-icon");this.j(a,"click",this.eU);this.api.createClientVe(a,this,115130);this.Ck();this.j(e,"autonavvisibility",this.Ck);this.j(e,"mdxnowautoplaying",this.wAF);this.j(e,"mdxautoplaycanceled",this.CvW);g.cD(this.element,"ytp-upnext-mobile",this.api.G().T)},VeG=function(e,a){if(a)return a;
if(e.api.isFullscreen()){var r;e=(r=e.api.getVideoData())==null?void 0:r.E$;return e===-1||e===void 0?8E3:e}return e.api.Zq()>=0?e.api.Zq():g.eS(e.api.G().experiments,"autoplay_time")||1E4},$fw=function(e,a){a=VeG(e,a);
var r=Math,P=r.min;var B=(0,g.Ov)()-e.T;r=P.call(r,B,a);a=a===0?1:Math.min(r/a,1);e.Z.setAttribute("stroke-dashoffset",""+-211*(a+1));a>=1&&e.UQ()&&e.api.getPresentingPlayerType()!==3?e.select(!0):e.UQ()&&e.S.start()},fb=function(e){Tv.call(this,e,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.v({K:"div",U:"ytp-suggestion-panel",V:[{K:"div",WW:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],S1:"More videos"}]});this.Y=new g.v({K:"div",U:"ytp-suggestions-container"});this.videos=[];this.B=null;this.Z=this.D=!1;this.T=new nb(this.player);g.x(this,this.T);this.T.Kf(this.element);e.getVideoData().Ge?this.S=this.T:(this.S=new XG(e),g.MY(this.player,this.S.element,4),g.x(this,this.S));this.overlay=new g.v({K:"div",
U:"ytp-autonav-overlay-cancelled-state"});g.x(this,this.overlay);this.overlay.Kf(this.element);this.L=new g.Zc(this);g.x(this,this.L);g.x(this,this.table);this.table.Kf(this.element);this.table.show();g.x(this,this.Y);this.Y.Kf(this.table.element);this.hide()},A$=function(e){var a=e.eK();
a!==e.Z&&(e.Z=a,teB(e.player),e.Z?(e.T!==e.S&&e.T.hide(),e.table.hide()):(e.T!==e.S&&e.T.show(),e.table.show()))},QJG=function(e){Tv.call(this,e,"videowall-endscreen");
var a=this;this.W=e;this.stills=[];this.B=this.videoData=null;this.L=this.D=!1;this.Y=null;g.rr(this.element,"modern-videowall-endscreen");this.T=new g.Zc(this);g.x(this,this.T);this.Z=new g.vP(function(){g.rr(a.element,"ytp-show-tiles")},0);
g.x(this,this.Z);this.table=new g.Ps({K:"div",U:"ytp-modern-endscreen-content"});g.x(this,this.table);this.table.Kf(this.element);e.getVideoData().Ge?this.S=new nb(e,!0):this.S=new XG(e);g.x(this,this.S);g.MY(this.player,this.S.element,4);e.createClientVe(this.element,this,158789);this.hide()},UB=function(e){return g.jn(e.player)&&e.GL()&&!e.B},Cb=function(e){var a=e.eK();
a!==e.D&&(e.D=a,teB(e.player))},W7a=function(e){Tv.call(this,e,"subscribecard-endscreen");
this.S=new g.v({K:"div",U:"ytp-subscribe-card",V:[{K:"img",U:"ytp-author-image",J:{src:"{{profilePicture}}"}},{K:"div",U:"ytp-subscribe-card-right",V:[{K:"div",U:"ytp-author-name",S1:"{{author}}"},{K:"div",U:"html5-subscribe-button-container"}]}]});g.x(this,this.S);this.S.Kf(this.element);var a=e.getVideoData();this.subscribeButton=new g.c6("Subscribe",null,"Unsubscribe",null,!0,!1,a.ix,a.subscribed,"trailer-endscreen",null,e,!1);g.x(this,this.subscribeButton);this.subscribeButton.Kf(this.S.BW("html5-subscribe-button-container"));
this.j(e,"videodatachange",this.zQ);this.zQ();this.hide()},Gv=function(e){var a=e.G(),r=g.Ed||g.MR?{style:"will-change: opacity"}:void 0,P=a.L,B=["ytp-videowall-still"];
a.T&&B.push("ytp-videowall-show-text");g.v.call(this,{K:"a",WW:B,J:{href:"{{url}}",target:P?a.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{K:"div",U:"ytp-videowall-still-image",J:{style:"{{background}}"}},{K:"span",U:"ytp-videowall-still-info",J:{"aria-hidden":"true"},V:[{K:"span",U:"ytp-videowall-still-info-bg",V:[{K:"span",U:"ytp-videowall-still-info-content",J:r,V:[{K:"span",U:"ytp-videowall-still-info-title",S1:"{{title}}"},
{K:"span",U:"ytp-videowall-still-info-author",S1:"{{author_and_views}}"},{K:"span",U:"ytp-videowall-still-info-live",S1:"Live"},{K:"span",U:"ytp-videowall-still-info-duration",S1:"{{duration}}"}]}]}]},{K:"span",WW:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},V:[{K:"span",U:"ytp-videowall-still-listlabel-icon"},"Playlist",{K:"span",U:"ytp-videowall-still-listlabel-length",V:[" (",{K:"span",S1:"{{playlist_length}}"},")"]}]},{K:"span",WW:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},V:[{K:"span",U:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{K:"span",U:"ytp-videowall-still-listlabel-length",S1:" (50+)"}]}]});this.suggestion=null;this.T=P;this.api=e;this.S=new g.Zc(this);g.x(this,this.S);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.S.j(e,"videodatachange",this.onVideoDataChange);e.createServerVe(this.element,this);this.onVideoDataChange()},EB=function(e){Tv.call(this,e,"videowall-endscreen");
var a=this;this.W=e;this.B=0;this.stills=[];this.L=this.videoData=null;this.Z=this.Y=!1;this.N=null;this.T=new g.Zc(this);g.x(this,this.T);this.D=new g.vP(function(){g.rr(a.element,"ytp-show-tiles")},0);
g.x(this,this.D);var r=new g.v({K:"button",WW:["ytp-button","ytp-endscreen-previous"],J:{"aria-label":"Previous"},V:[g.fB()]});g.x(this,r);r.Kf(this.element);r.listen("click",this.UV,this);this.table=new g.Ps({K:"div",U:"ytp-endscreen-content"});g.x(this,this.table);this.table.Kf(this.element);r=new g.v({K:"button",WW:["ytp-button","ytp-endscreen-next"],J:{"aria-label":"Next"},V:[g.A_()]});g.x(this,r);r.Kf(this.element);r.listen("click",this.DJ,this);e.getVideoData().Ge?this.S=new nb(e,!0):this.S=
new XG(e);g.x(this,this.S);g.MY(this.player,this.S.element,4);e.createClientVe(this.element,this,158789);this.hide()},bm=function(e){return g.jn(e.player)&&e.GL()&&!e.L},t$=function(e){var a=e.eK();
a!==e.Y&&(e.Y=a,teB(e.player))},lel=function(e,a){g.v.call(this,{K:"button",
WW:["ytp-watch-on-youtube-button","ytp-button"],S1:"{{content}}"});this.W=e;this.buttonType=this.buttonType=a;this.q7();this.buttonType===2&&g.rr(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.q7);this.Nr(!0)},gD=function(e){Tv.call(this,e,"watch-again-on-youtube-endscreen");
this.watchButton=new lel(e,1);g.x(this,this.watchButton);this.watchButton.Kf(this.element);g.GVM(e)&&(this.S=new g.ap(e),g.x(this,this.S),this.T=new g.v({K:"div",WW:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],J:{tabIndex:"-1"},V:[this.S]}),g.x(this,this.T),this.S.Kf(this.T.element),this.T.Kf(this.element));e.createClientVe(this.element,this,156914);this.hide()},pea=function(e){g.Vn.call(this,e);
var a=this;this.endScreen=null;this.S=this.T=this.B=!1;this.listeners=new g.Zc(this);g.x(this,this.listeners);var r=e.G();e.isEmbedsShortsMode()?this.endScreen=new gD(e):L7w(e)?(this.B=!0,Yn8(this),this.S?this.endScreen=new fb(e):r.X("delhi_modern_endscreen")?this.endScreen=new QJG(e):this.endScreen=new EB(e)):r.BV?this.endScreen=new W7a(e):this.endScreen=new Tv(e);g.x(this,this.endScreen);g.MY(e,this.endScreen.element,4);wea(this);this.listeners.j(e,"videodatachange",this.onVideoDataChange,this);
this.listeners.j(e,g.SS("endscreen"),function(P){a.onCueRangeEnter(P)});
this.listeners.j(e,g.sh("endscreen"),function(P){a.onCueRangeExit(P)})},Yn8=function(e){var a=e.player.getVideoData();
if(!a||e.S===a.Rs&&e.T===a.Ge)return!1;e.S=a.Rs;e.T=a.Ge;return!0},L7w=function(e){e=e.G();
return e.Ge&&!e.BV&&!e.disableOrganicUi},wea=function(e){e.player.Ai("endscreen");
var a=e.player.getVideoData();a=new g.v_(Math.max((a.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var r=new g.v_(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});e.player.Ji([a,r])};
g.Hx.prototype.Zq=g.BI(6,function(){return this.app.Zq()});
g.gZ.prototype.Zq=g.BI(5,function(){return this.getVideoData().KH});
g.zg.prototype.zc=g.BI(4,function(e){this.ZW().zc(e)});
g.Kk.prototype.zc=g.BI(3,function(e){this.hG!==e&&(this.hG=e,this.JN())});
g.b(oC,g.v);oC.prototype.select=function(){this.W.nY(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Wf||void 0)&&this.W.logClick(this.element)};
oC.prototype.onClick=function(e){g.ke(e,this.W,this.S,this.suggestion.sessionData||void 0)&&this.select()};
oC.prototype.onKeyPress=function(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}};g.b(nb,g.v);g.E=nb.prototype;g.E.Cz=function(e){this.suggestion!==e&&(this.suggestion=e,g.Ah(this.S,e),this.playButton.updateValue("url",this.suggestion.Um()),yh(this))};
g.E.UQ=function(){return this.B>0};
g.E.Jc=function(){this.UQ()||(this.B=Date.now(),kTV(this),g3a(this.W,JVG(this)),g.cD(this.W.getRootNode(),"countdown-running",this.UQ()))};
g.E.a5=function(){this.TJ();kTV(this);var e=this.S.BW("ytp-autonav-endscreen-upnext-header");e&&g.ZF(e,"Up next")};
g.E.TJ=function(){this.UQ()&&(this.L.stop(),this.B=0)};
g.E.select=function(e){this.W.nextVideo(!1,e===void 0?!1:e);this.TJ()};
g.E.Zu=function(e){g.ke(e,this.W)&&(e.currentTarget===this.playButton.element?this.W.logClick(this.playButton.element):e.currentTarget===this.S.BW("ytp-autonav-endscreen-link-container")&&(e=this.S.BW("ytp-autonav-endscreen-link-container"),this.W.logVisibility(e,!0),this.W.logClick(e)),this.Z?(this.W.qF("innertubeCommand",this.Z),this.TJ()):this.select())};
g.E.Kw=function(){this.W.logClick(this.cancelButton.element);g.vx(this.W,!0);this.cancelCommand&&this.W.qF("innertubeCommand",this.cancelCommand)};
g.E.onVideoDataChange=function(e,a){O6N(this,a);e=a.getWatchNextResponse();var r,P;e=(r=Z6G(e))==null?void 0:(P=r.cancelButton)==null?void 0:P.buttonRenderer;this.cancelCommand=e==null?void 0:e.command};
g.E.sHM=function(e){if(Dfl(this)){var a=this.W.getVideoData().watchToWatchTransitionRenderer,r=a==null?void 0:a.fromColorPaletteDark;a=a==null?void 0:a.toColorPaletteDark;if(r&&a){var P=this.element;P.style.setProperty("--w2w-start-background-color",g.Yg(r.surgeColor));P.style.setProperty("--w2w-start-primary-text-color",g.Yg(r.primaryTitleColor));P.style.setProperty("--w2w-start-secondary-text-color",g.Yg(r.secondaryTitleColor));P.style.setProperty("--w2w-end-background-color",g.Yg(a.surgeColor));
P.style.setProperty("--w2w-end-primary-text-color",g.Yg(a.primaryTitleColor));P.style.setProperty("--w2w-end-secondary-text-color",g.Yg(a.secondaryTitleColor));P.style.setProperty("--w2w-animation-duration",e+"ms")}g.cD(this.element,"ytp-w2w-animate",!0)}};
g.E.EV=function(e){this.W.X("web_autonav_color_transition")&&e!==2&&g.cD(this.element,"ytp-w2w-animate",!1)};
g.E.l_=function(){var e=this.W.eK();this.D&&this.oD!==e&&this.Nr(e);yh(this);this.W.logVisibility(this.container.element,e);this.W.logVisibility(this.cancelButton.element,e);this.W.logVisibility(this.S.BW("ytp-autonav-endscreen-link-container"),e);this.W.logVisibility(this.playButton.element,e)};
g.E.tA=function(e){return e.width<400||e.height<459};g.b(Tv,g.v);g.E=Tv.prototype;g.E.create=function(){this.created=!0};
g.E.destroy=function(){this.created=!1};
g.E.GL=function(){return!1};
g.E.eK=function(){return!1};
g.E.Rt=function(){return!1};g.b(XG,g.v);g.E=XG.prototype;g.E.i4=function(){this.notification&&(this.L.stop(),this.Xo(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.E.Cz=function(e){this.suggestion=e;g.Ah(this,e,"hqdefault.jpg")};
g.E.Ck=function(){this.Nr(this.api.eK());this.api.logVisibility(this.element,this.api.eK());this.api.logVisibility(this.BW("ytp-upnext-autoplay-icon"),this.api.eK());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.eK())};
g.E.zzz=function(){window.focus();this.i4()};
g.E.Jc=function(e){var a=this;this.UQ()||(g.Ku("a11y-announce","Up Next "+this.suggestion.title),this.T=(0,g.Ov)(),this.S=new g.vP(function(){$fw(a,e)},25),$fw(this,e),g3a(this.api,VeG(this,e)));
g.BD(this.element,"ytp-upnext-autoplay-paused")};
g.E.hide=function(){g.v.prototype.hide.call(this)};
g.E.UQ=function(){return!!this.S};
g.E.a5=function(){this.TJ();this.T=(0,g.Ov)();$fw(this);g.rr(this.element,"ytp-upnext-autoplay-paused")};
g.E.TJ=function(){this.UQ()&&(this.S.dispose(),this.S=null)};
g.E.select=function(e){e=e===void 0?!1:e;if(this.api.G().X("autonav_notifications")&&e&&window.Notification&&typeof document.hasFocus==="function"){var a=Notification.permission;a==="default"?Notification.requestPermission():a!=="granted"||document.hasFocus()||(this.i4(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.EG()}),this.B=this.j(this.notification,"click",this.zzz),this.L.start())}this.TJ();this.api.nextVideo(!1,e)};
g.E.eU=function(e){!g.gy(this.cancelButton.element,e.target)&&g.ke(e,this.api)&&(this.api.eK()&&this.api.logClick(this.BW("ytp-upnext-autoplay-icon")),this.select())};
g.E.WF=function(){this.api.eK()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.vx(this.api,!0)};
g.E.wAF=function(e){this.api.getPresentingPlayerType();this.show();this.Jc(e)};
g.E.CvW=function(){this.api.getPresentingPlayerType();this.TJ();this.hide()};
g.E.RH=function(){this.TJ();this.i4();g.v.prototype.RH.call(this)};g.b(fb,Tv);g.E=fb.prototype;g.E.create=function(){Tv.prototype.create.call(this);this.L.j(this.player,"appresize",this.wf);this.L.j(this.player,"onVideoAreaChange",this.wf);this.L.j(this.player,"videodatachange",this.onVideoDataChange);this.L.j(this.player,"autonavchange",this.Xs);this.L.j(this.player,"onAutonavCancelled",this.ZJ);this.onVideoDataChange()};
g.E.show=function(){Tv.prototype.show.call(this);(this.D||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.vx(this.player,!1);g.jn(this.player)&&this.GL()&&!this.B?(A$(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Jc():this.videoData.autonavState===3&&this.S.a5()):(g.vx(this.player,!0),A$(this));this.wf()};
g.E.hide=function(){Tv.prototype.hide.call(this);this.S.a5();A$(this)};
g.E.wf=function(){var e=this.player.jZ(!0,this.player.isFullscreen());A$(this);yh(this.T);g.cD(this.element,"ytp-autonav-cancelled-small-mode",this.tA(e));g.cD(this.element,"ytp-autonav-cancelled-tiny-mode",this.AZ(e));g.cD(this.element,"ytp-autonav-cancelled-mini-mode",e.width<=400||e.height<=360);this.overlay&&g.vo(this.overlay.element,{width:e.width+"px"});if(!this.Z)for(e=0;e<this.videos.length;e++)g.cD(this.videos[e].element,"ytp-suggestion-card-with-margin",e%2===1)};
g.E.onVideoDataChange=function(){var e=this.player.getVideoData();if(this.videoData!==e&&e){this.videoData=e;if((e=this.videoData.suggestions)&&e.length||this.player.X("web_player_autonav_empty_suggestions_fix")){var a=g.Zo(this.videoData);a&&(this.S.Cz(a),this.S!==this.T&&this.T.Cz(a))}if(e&&e.length)for(a=0;a<i6N.length;++a){var r=i6N[a];if(e&&e[r]){this.videos[a]=new oC(this.player);var P=this.videos[a];r=e[r];P.suggestion!==r&&(P.suggestion=r,g.Ah(P,r));g.x(this,this.videos[a]);this.videos[a].Kf(this.Y.element)}}this.wf()}};
g.E.Xs=function(e){e===1?(this.D=!1,this.B=this.videoData.clientPlaybackNonce,this.S.TJ(),this.oD&&this.wf()):(this.D=!0,this.eK()&&(e===2?this.S.Jc():e===3&&this.S.a5()))};
g.E.ZJ=function(e){e?this.Xs(1):(this.B=null,this.D=!1)};
g.E.GL=function(){return this.videoData.autonavState!==1};
g.E.tA=function(e){return(e.width<910||e.height<459)&&!this.AZ(e)&&!(e.width<=400||e.height<=360)};
g.E.AZ=function(e){return e.width<800&&!(e.width<=400||e.height<=360)};
g.E.eK=function(){return this.oD&&g.jn(this.player)&&this.GL()&&!this.B};
var i6N=[1,3,2,4];g.b(QJG,Tv);g.E=QJG.prototype;g.E.create=function(){Tv.prototype.create.call(this);var e=this.player.getVideoData();e&&(this.videoData=e);this.gR();this.T.j(this.player,"appresize",this.gR);this.T.j(this.player,"onVideoAreaChange",this.gR);this.T.j(this.player,"videodatachange",this.onVideoDataChange);this.T.j(this.player,"autonavchange",this.nZ);this.T.j(this.player,"onAutonavCancelled",this.Cw);e=this.videoData.autonavState;e!==this.Y&&this.nZ(e);this.T.j(this.element,"transitionend",this.XC)};
g.E.destroy=function(){g.du(this.T);g.Be(this.stills);this.stills=[];Tv.prototype.destroy.call(this);g.BD(this.element,"ytp-show-tiles");this.Z.stop();this.Y=this.videoData.autonavState};
g.E.GL=function(){return this.videoData.autonavState!==1};
g.E.show=function(){var e=this.oD;Tv.prototype.show.call(this);g.BD(this.element,"ytp-show-tiles");this.player.G().T?g.ms(this.Z):this.Z.start();(this.L||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.vx(this.player,!1);UB(this)?(Cb(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Jc():this.videoData.autonavState===3&&this.S.a5()):(g.vx(this.player,!0),Cb(this));e!==this.oD&&this.player.logVisibility(this.element,!0)};
g.E.hide=function(){var e=this.oD;Tv.prototype.hide.call(this);this.S.a5();Cb(this);e!==this.oD&&this.player.logVisibility(this.element,!1)};
g.E.XC=function(e){e.target===this.element&&this.gR()};
g.E.gR=function(){var e,a,r,P;var B=((e=this.videoData)==null?0:(a=e.suggestions)==null?0:a.length)?(r=this.videoData)==null?void 0:r.suggestions:[(P=this.videoData)==null?void 0:g.Zo(P)];if(B.length){a=this.W.jZ(!0,this.W.isFullscreen());e=Math.floor((a.width-64+16)/(g.ID(a.width*.27,250,450)+16));a=Math.min(3,Math.floor((a.height-64)/((a.width-64-(e-1)*16)/e*.5625+70)));g.hi(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.rr(this.element,"ytp-modern-endscreen-limit-rows-"+a);g.cD(this.element,"ytp-modern-endscreen-single-item",e===1);g.cD(this.element,"ytp-modern-endscreen-row-0",a===0);e=this.table.element;e.ariaLive="polite";this.S.Cz(g.Zo(this.videoData));this.S instanceof nb&&yh(this.S);g.cD(this.element,"ytp-endscreen-takeover",UB(this));Cb(this);a=0;e.ariaBusy="true";r=B.length;for(P=0;P<r;P++){var h=P%r,c=this.stills[P];c||(c=new g.U4(this.player),this.stills[P]=c,e.appendChild(c.element));g.bF3(c,B[h]);a++}this.stills.length=
a}};
g.E.onVideoDataChange=function(){var e=this.player.getVideoData(1);this.videoData!==e&&(e!=null&&g.Zo(e)?(this.videoData=e,this.gR()):this.player.nf("missg",{vid:(e==null?void 0:e.videoId)||"",cpn:(e==null?void 0:e.clientPlaybackNonce)||""}))};
g.E.Rt=function(){return this.S.UQ()};
g.E.nZ=function(e){e===1?(this.L=!1,this.B=this.videoData.clientPlaybackNonce,this.S.TJ(),this.oD&&this.gR()):(this.L=!0,this.oD&&UB(this)&&(e===2?this.S.Jc():e===3&&this.S.a5()))};
g.E.Cw=function(e){if(e){for(e=0;e<this.stills.length;e++)this.W.logVisibility(this.stills[e].element,!0);this.nZ(1)}else this.B=null,this.L=!1;this.gR()};
g.E.eK=function(){return this.oD&&UB(this)};g.b(W7a,Tv);W7a.prototype.zQ=function(){var e=this.player.getVideoData();this.S.update({profilePicture:e.profilePicture,author:e.author});this.subscribeButton.channelId=e.ix;var a=this.subscribeButton;e.subscribed?a.S():a.T()};g.b(Gv,g.v);Gv.prototype.select=function(){this.api.nY(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Wf||void 0)&&this.api.logClick(this.element)};
Gv.prototype.onClick=function(e){if(g.uP(this.api.G())&&this.api.X("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var a=this.suggestion.Um(),r={};g.sL(this.api,r);a=g.EW(a,r);g.da(a,this.api,e)}else g.ke(e,this.api,this.T,this.suggestion.sessionData||void 0)&&this.select()};
Gv.prototype.onKeyPress=function(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}};
Gv.prototype.onVideoDataChange=function(){var e=this.api.getVideoData(),a=this.api.G();this.T=e.nB?!1:a.L};g.b(EB,Tv);g.E=EB.prototype;g.E.create=function(){Tv.prototype.create.call(this);var e=this.player.getVideoData();e&&(this.videoData=e);this.iP();this.T.j(this.player,"appresize",this.iP);this.T.j(this.player,"onVideoAreaChange",this.iP);this.T.j(this.player,"videodatachange",this.onVideoDataChange);this.T.j(this.player,"autonavchange",this.S4);this.T.j(this.player,"onAutonavCancelled",this.Qp);e=this.videoData.autonavState;e!==this.N&&this.S4(e);this.T.j(this.element,"transitionend",this.jU)};
g.E.destroy=function(){g.du(this.T);g.Be(this.stills);this.stills=[];Tv.prototype.destroy.call(this);g.BD(this.element,"ytp-show-tiles");this.D.stop();this.N=this.videoData.autonavState};
g.E.GL=function(){return this.videoData.autonavState!==1};
g.E.show=function(){var e=this.oD;Tv.prototype.show.call(this);g.BD(this.element,"ytp-show-tiles");this.player.G().T?g.ms(this.D):this.D.start();(this.Z||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.vx(this.player,!1);bm(this)?(t$(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.Jc():this.videoData.autonavState===3&&this.S.a5()):(g.vx(this.player,!0),t$(this));e!==this.oD&&this.player.logVisibility(this.element,!0)};
g.E.hide=function(){var e=this.oD;Tv.prototype.hide.call(this);this.S.a5();t$(this);e!==this.oD&&this.player.logVisibility(this.element,!1)};
g.E.jU=function(e){e.target===this.element&&this.iP()};
g.E.iP=function(){var e,a,r,P;var B=((e=this.videoData)==null?0:(a=e.suggestions)==null?0:a.length)?(r=this.videoData)==null?void 0:r.suggestions:[(P=this.videoData)==null?void 0:g.Zo(P)];if(B.length){g.rr(this.element,"ytp-endscreen-paginate");var h=this.W.jZ(!0,this.W.isFullscreen());if(e=g.lL(this.W))e=e.eX()?48:32,h.width-=e*2;var c=h.width/h.height;P=96/54;a=e=2;var y=Math.max(h.width/96,2),T=Math.max(h.height/54,2);r=B.length;var X=r*4;for(X-=4;X>0&&(e<y||a<T);){var f=e/2,A=a/2,U=e<=y-2&&X>=
A*4,C=a<=T-2&&X>=f*4;if((f+1)/A*P/c>c/(f/(A+1)*P)&&C)X-=f*4,a+=2;else if(U)X-=A*4,e+=2;else if(C)X-=f*4,a+=2;else break}P=!1;X>=12&&r*4-X<=6&&(a>=4||e>=4)&&(P=!0);X=e*96;y=a*54;c=X/y<c?h.height/y:h.width/X;c=Math.min(c,2);X=Math.floor(Math.min(h.width,X*c));y=Math.floor(Math.min(h.height,y*c));h=this.table.element;h.ariaLive="polite";g.ab(h,X,y);g.vo(h,{marginLeft:X/-2+"px",marginTop:y/-2+"px"});this.S.Cz(g.Zo(this.videoData));this.S instanceof nb&&yh(this.S);g.cD(this.element,"ytp-endscreen-takeover",
bm(this));t$(this);X+=4;y+=4;c=0;h.ariaBusy="true";for(T=0;T<e;T++)for(f=0;f<a;f++)if(A=c,C=0,P&&T>=e-2&&f>=a-2?C=1:f%2===0&&T%2===0&&(f<2&&T<2?f===0&&T===0&&(C=2):C=2),A=g.HR(A+this.B,r),C!==0){U=this.stills[c];U||(U=new Gv(this.player),this.stills[c]=U,h.appendChild(U.element));var G=Math.floor(y*f/a),O=Math.floor(X*T/e),d=Math.floor(y*(f+C)/a)-G-4,W=Math.floor(X*(T+C)/e)-O-4;g.j2(U.element,O,G);g.ab(U.element,W,d);g.vo(U.element,"transitionDelay",(f+T)/20+"s");g.cD(U.element,"ytp-videowall-still-mini",
C===1);g.cD(U.element,"ytp-videowall-still-large",C>2);C=Math.max(W,d);g.cD(U.element,"ytp-videowall-still-round-large",C>=256);g.cD(U.element,"ytp-videowall-still-round-medium",C>96&&C<256);g.cD(U.element,"ytp-videowall-still-round-small",C<=96);A=B[A];U.suggestion!==A&&(U.suggestion=A,C=U.api.G(),G=g.ac(U.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Ah(U,A,G),g.uP(C)&&!U.api.X("web_player_log_click_before_generating_ve_conversion_params")&&(C=A.Um(),G={},g.Da(U.api,"addEmbedsConversionTrackingParams",
[G]),C=g.EW(C,G),U.updateValue("url",C)),(A=(A=A.sessionData)&&A.itct)&&U.api.setTrackingParams(U.element,A));c++}h.ariaBusy="false";g.cD(this.element,"ytp-endscreen-paginate",c<r);for(B=this.stills.length-1;B>=c;B--)e=this.stills[B],g.t5(e.element),g.Pe(e);this.stills.length=c}};
g.E.onVideoDataChange=function(){var e=this.player.getVideoData(1);this.videoData!==e&&(e!=null&&g.Zo(e)?(this.B=0,this.videoData=e,this.iP()):this.player.nf("missg",{vid:(e==null?void 0:e.videoId)||"",cpn:(e==null?void 0:e.clientPlaybackNonce)||""}))};
g.E.DJ=function(){this.B+=this.stills.length;this.iP()};
g.E.UV=function(){this.B-=this.stills.length;this.iP()};
g.E.Rt=function(){return this.S.UQ()};
g.E.S4=function(e){e===1?(this.Z=!1,this.L=this.videoData.clientPlaybackNonce,this.S.TJ(),this.oD&&this.iP()):(this.Z=!0,this.oD&&bm(this)&&(e===2?this.S.Jc():e===3&&this.S.a5()))};
g.E.Qp=function(e){if(e){for(e=0;e<this.stills.length;e++)this.W.logVisibility(this.stills[e].element,!0);this.S4(1)}else this.L=null,this.Z=!1;this.iP()};
g.E.eK=function(){return this.oD&&bm(this)};g.b(lel,g.v);g.E=lel.prototype;g.E.q7=function(){switch(this.buttonType){case 1:var e="Watch again on YouTube";var a=156915;break;case 2:e="Continue watching on YouTube";a=156942;break;default:e="Continue watching on YouTube",a=156942}this.update({content:e});this.W.hasVe(this.element)&&this.W.destroyVe(this.element);this.W.createClientVe(this.element,this,a)};
g.E.onClick=function(e){this.W.X("web_player_log_click_before_generating_ve_conversion_params")&&this.W.logClick(this.element);g.da(this.getVideoUrl(),this.W,e);this.W.X("web_player_log_click_before_generating_ve_conversion_params")||this.W.logClick(this.element)};
g.E.getVideoUrl=function(){var e=!0;switch(this.buttonType){case 1:e=!0;break;case 2:e=!1}e=this.W.getVideoUrl(e,!1,!1,!0);var a=this.W.G();if(g.uP(a)){var r={};g.uP(a)&&g.Da(this.W,"addEmbedsConversionTrackingParams",[r]);e=g.EW(e,r)}return e};
g.E.logVisibility=function(){this.W.logVisibility(this.element,this.oD&&this.C)};
g.E.show=function(){g.v.prototype.show.call(this);this.logVisibility()};
g.E.hide=function(){g.v.prototype.hide.call(this);this.logVisibility()};
g.E.Yy=function(e){g.v.prototype.Yy.call(this,e);this.logVisibility()};g.b(gD,Tv);gD.prototype.hasSuggestions=function(){var e;return(e=this.S)==null?void 0:e.hasSuggestions()};
gD.prototype.show=function(){if(this.player.getPlayerState()!==3){Tv.prototype.show.call(this);var e=this.T;if(e){var a=this.S.hasSuggestions();g.cD(this.element,"ytp-shorts-branded-ui",a);a?e.show():e.hide()}var r;(r=g.lL(this.player))==null||r.zc(!0);this.player.logVisibility(this.element,!0);this.watchButton.Yy(!0)}};
gD.prototype.hide=function(){Tv.prototype.hide.call(this);var e;(e=g.lL(this.player))==null||e.zc(!1);this.player.logVisibility(this.element,!1);this.watchButton.Yy(!1)};g.b(pea,g.Vn);g.E=pea.prototype;g.E.VB=function(){var e=this.player.getVideoData(),a=e.mutedAutoplay&&(e.limitedPlaybackDurationInSeconds>0||e.endSeconds>0||e.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!a)return!0;var r;var P=!!((e==null?0:g.Zo(e))||(e==null?0:(r=e.suggestions)==null?0:r.length));P=!L7w(this.player)||P;e=e.G0;r=this.player.BM();return P&&!e&&!r&&!a};
g.E.eK=function(){return this.endScreen.eK()};
g.E.Wl=function(){return this.eK()?this.endScreen.Rt():!1};
g.E.RH=function(){this.player.Ai("endscreen");g.Vn.prototype.RH.call(this)};
g.E.load=function(){var e=this.player.getVideoData();var a=e.transitionEndpointAtEndOfStream;if(a&&a.videoId){var r=this.player.eO().oL.get("heartbeat"),P=g.Zo(e);!P||a.videoId!==P.videoId||e.q_?(this.player.nY(a.videoId,void 0,void 0,!0,!0,a),r&&r.Mh("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),e=!0):e=!1}else e=!1;e||(g.Vn.prototype.load.call(this),this.endScreen.show())};
g.E.unload=function(){g.Vn.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.E.onCueRangeEnter=function(e){this.VB()&&(this.endScreen.created||this.endScreen.create(),e.getId()==="load"&&this.load())};
g.E.onCueRangeExit=function(e){e.getId()==="load"&&this.loaded&&this.unload()};
g.E.onVideoDataChange=function(){wea(this);this.B&&Yn8(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.S?this.endScreen=new fb(this.player):this.endScreen=new EB(this.player),g.x(this,this.endScreen),g.MY(this.player,this.endScreen.element,4))};g.DD("endscreen",pea);})(_yt_player);
